import test from 'node:test';
import assert from 'node:assert/strict';
import {calculate,normalize} from '../src/engine.js';
import {defaults,hardware,models} from '../src/catalog.js';
const calc=x=>calculate({...defaults,...x});
test('volume and auto concurrency are separate',()=>{const r=calc({users:10,agents:2,activity:25,requests:100,days:20});assert.equal(r.requests,40000);assert.equal(r.batch,5);assert.equal(calc({activity:0}).requests,calc({activity:100}).requests);});
test('all experts count toward memory and batching multiplies cache',()=>{const a=calc({batch:1}),b=calc({batch:4});assert.equal(a.weight,46);assert.equal(b.cache,a.cache*4);assert.equal(b.weight,a.weight);});
test('precision changes weight requirements',()=>assert.equal(calc({bits:8}).weight,calc({bits:4}).weight*2));
test('OOM disables local savings, preserving full API expense',()=>{const r=calc({memory:1});assert.equal(r.localRequests,0);assert.equal(r.overflow,r.cloud);assert.equal(r.payback,null);assert.equal(r.thresholdFeasible,false);});
test('invalid model context disables local serving',()=>{for(const x of [{context:1},{context:1048576}])assert.equal(calc(x).localRequests,0);});
test('API cache and input/output use distinct prices',()=>{const r=calc({users:1,agents:1,requests:1,days:1,input:100000,output:10000,context:131072,apiInput:2,apiCached:0.2,cache:50,apiOutput:10});assert.ok(Math.abs(r.cloud-.21)<1e-10);});
test('zero work and free API never invent payback',()=>{assert.equal(calc({users:0}).cloud,0);assert.equal(calc({apiInput:0,apiOutput:0,apiCached:0}).payback,null);});
test('capacity is enforced and overflow is charged',()=>{const r=calc({users:1000,requests:1000,hours:1,batch:1});assert.ok(r.localFraction<1);assert.ok(r.overflow>0);assert.ok(Math.abs(r.localRequests-r.capacity)<1e-8);});
test('no serving time means all demand overflows',()=>{const r=calc({hours:0});assert.equal(r.localRequests,0);assert.equal(r.overflow,r.cloud);});
test('hand-calculated cash flow and resale',()=>{const r=calc({users:1,agents:1,requests:1,days:1,input:0,output:1000,apiOutput:100000,price:1000,setup:200,idle:0,load:0,maintenance:10,months:12,resale:50});assert.equal(r.cloud,100);assert.equal(r.recurring,10);assert.equal(r.payback,1200/90);assert.equal(r.localTco,820);assert.equal(r.cloudTco,1200);});
test('idle power is paid all month',()=>{const r=calc({users:0,idle:100,load:100,cooling:1,electricity:0.5});assert.equal(r.energyKwh,72);assert.equal(r.powerCost,36);});
test('manual rate override and sublinear batch speed',()=>{const r=calc({decodeOverride:100,batch:4,batchExponent:0.5,speed:50});assert.equal(r.decode,100);assert.equal(r.perStream,25);});
test('no throughput means no local capacity and finite cash flow',()=>{const r=calc({speed:0});assert.equal(r.localRequests,0);assert.ok(Number.isFinite(r.localTco));assert.equal(r.activeHours,0);});
test('normalization guards nonfinite and invalid inputs',()=>{const s=normalize({...defaults,price:NaN,cache:1000,days:100,hours:100,months:0});assert.equal(s.price,defaults.price);assert.equal(s.cache,100);assert.equal(s.days,30);assert.equal(s.hours,24);assert.equal(s.months,1);});
test('catalog combinations remain finite and memory fit is enforced',()=>{for(const m of models)for(const h of hardware){const r=calc({model:m.id,hardware:h.id,...Object.fromEntries(['price','memory','reserve','idle','load'].map(k=>[k,h[k]]))});assert.ok(Number.isFinite(r.localTco));assert.ok(Number.isFinite(r.cloudTco));assert.ok(r.localFraction>=0&&r.localFraction<=1);if(!r.fits)assert.equal(r.localRequests,0);}});
test('rental monthly cost and TCO include setup and all billed hours',()=>{const r=calc({users:0,rental:3,rentalHours:200,rentalExtra:25,rentalSetup:100,months:12});assert.equal(r.rentalMonthly,625);assert.equal(r.rentalTco,7600);});
test('rental memory failure charges full API demand plus rental invoice',()=>{const r=calc({rentalMemory:1});assert.equal(r.rentalRequests,0);assert.equal(r.rentalOverflow,r.cloud);assert.equal(r.rentalMonthly,r.rentalCompute+r.s.rentalExtra+r.cloud);});
test('rental and purchase have independent memory and capacity',()=>{const r=calc({memory:1,rentalMemory:512,rentalReserve:0});assert.equal(r.localRequests,0);assert.ok(r.rentalRequests>0);});
test('zero rental hours sends all demand to API',()=>{const r=calc({rentalHours:0});assert.equal(r.rentalCapacity,0);assert.equal(r.rentalOverflow,r.cloud);});
test('rental bills idle provisioned hours but cannot serve outside workload window',()=>{const a=calc({rentalHours:176}),b=calc({rentalHours:720});assert.equal(a.rentalCapacity,b.rentalCapacity);assert.ok(b.rentalMonthly>a.rentalMonthly);});
test('rental decode override and utilization produce hand-calculated capacity',()=>{const r=calc({input:0,output:1000,batch:1,rentalDecodeOverride:100,rentalSpeed:100,rentalEfficiency:50,rentalHours:10,users:100,requests:1000});assert.equal(r.rentalCapacity,1800);assert.equal(r.rentalRequests,1800);assert.ok(r.rentalOverflow>0);});
test('purchase versus rental payback accounts for both upfront costs',()=>{const r=calc({users:0,price:1000,setup:200,idle:0,load:0,maintenance:10,rentalSetup:200,rental:1,rentalHours:100,rentalExtra:10});assert.equal(r.paybackVsRental,10);});
test('rental invalid context and zero speed have finite cash flows',()=>{for(const x of [{context:1},{rentalSpeed:0}]){const r=calc(x);assert.equal(r.rentalRequests,0);assert.ok(Number.isFinite(r.rentalTco));}});
test('matching hardware assumptions yield equal serving capacity',()=>{const r=calc({hardware:'h100',memory:160,reserve:10,rentalHardware:'h100',rentalMemory:160,rentalReserve:10});assert.equal(r.capacity,r.rentalCapacity);assert.equal(r.localRequests,r.rentalRequests);});
