import test from 'node:test';
import assert from 'node:assert/strict';
import {defaults,hardware,applyWorkload} from '../src/catalog.js';
import {normalize,calculate} from '../src/engine.js';
import {optimize,candidates,hardwareState,autoHorizon} from '../src/planner.js';
import {encodeState,decodeState} from '../src/sharing.js';
test('task changes choose shortlist model and lowest purchase budget with capacity',()=>{const s=optimize(applyWorkload({...defaults},'swe'));const c=candidates(s);assert.equal(s.model,'qwen80');assert.equal(s.hardware,c[0].h.id);assert.ok(c[0].r.localFraction>=.999);assert.ok(c.filter(x=>x.r.localFraction>=.999).every(x=>x.h.price>=s.price));});
test('manual choices survive upstream changes',()=>{const s=optimize({...defaults,autoModel:0,autoHardware:0,model:'kimi3',hardware:'spark',users:100});assert.equal(s.model,'kimi3');assert.equal(s.hardware,'spark');});
test('Kimi K3 requires a cluster at Q4 and fits four 512GB Macs in estimate',()=>{const s=optimize({...applyWorkload(defaults,'chat'),autoModel:0,model:'kimi3',kv:.1});assert.equal(s.hardware,'m5-512-x4');assert.ok(calculate(s).fits);assert.ok(!calculate(hardwareState(s,hardware.find(h=>h.id==='m5-512'))).fits);});
test('cluster costs memory and power cover all nodes, performance sublinear',()=>{const base=hardware.find(h=>h.id==='spark'),cluster=hardware.find(h=>h.id==='spark-x4');assert.equal(cluster.memory,base.memory*4);assert.ok(cluster.price>base.price*4);assert.ok(cluster.load>=base.load*4);assert.ok(cluster.decode<base.decode*4);});
test('matched rental overrides stale independent assumptions and has equal capacity',()=>{const r=calculate({...defaults,rentalHours:176,matchHardware:1,rentalMemory:1,rentalSpeed:0,rentalDecodeOverride:500});assert.equal(r.capacity,r.rentalCapacity);assert.equal(r.decode,r.rentalDecode);assert.equal(r.available,r.rentalAvailable);});
test('no viable hardware is not reported as a fit',()=>{const s=optimize({...defaults,autoModel:0,model:'kimi3',bits:16});assert.equal(candidates(s).length,0);assert.equal(calculate(s).fits,false);});
test('automatic horizon follows later payback and caps extreme forecasts',()=>{const s={...defaults,users:1,agents:1,requests:1,days:1,input:0,output:1000,apiOutput:100000,price:1000,setup:200,idle:0,load:0,maintenance:10,rental:1,rentalHours:100,rentalExtra:10};const h=autoHorizon(s);assert.equal(h.payback,1200/90);assert.equal(h.months,18);assert.equal(autoHorizon({...s,price:1e7}).months,120);assert.equal(autoHorizon({...s,apiOutput:0}).months,60);});
test('URL roundtrip preserves every form input except calculated horizon',()=>{const s=normalize({...defaults,model:'kimi3',hardware:'m5-512-x4',autoModel:0,autoHardware:0,matchHardware:0,rentalHardware:'spark-x4',rental:9.87,price:54321,users:42,months:60});const decoded=decodeState('?'+encodeState(s));for(const k of Object.keys(defaults))if(k!=='months')assert.equal(decoded[k],s[k],k);assert.equal(decodeState('?release=123'),null);assert.equal(decodeState('?scenario=1&users=NaN&model=bad').model,defaults.model);});

test('lifecycle flags both refresh windows and memory pressure independently',async()=>{const {lifecycleRisk}=await import('../src/planner.js');const r=calculate({...defaults,modelRefresh:3,hardwareRefresh:12,nextModelGrowth:2});const long={...r,payback:24,paybackVsRental:18,weight:80,cache:10,available:150};const risk=lifecycleRisk(long);assert.equal(risk.payback,24);assert.equal(risk.modelRisk,true);assert.equal(risk.hardwareRisk,true);assert.equal(risk.nextFits,false);assert.equal(risk.nextRequired,170);assert.equal(risk.weightHeadroom,1.75);assert.equal(lifecycleRisk({...long,available:200}).nextFits,true);});
test('lifecycle boundary is strictly after the review window',async()=>{const {lifecycleRisk}=await import('../src/planner.js');const r=calculate({...defaults,modelRefresh:3,hardwareRefresh:12});assert.equal(lifecycleRisk({...r,payback:3,paybackVsRental:2}).warning,false);const medium=lifecycleRisk({...r,payback:6,paybackVsRental:4});assert.equal(medium.modelRisk,true);assert.equal(medium.hardwareRisk,false);assert.equal(lifecycleRisk({...r,payback:null}).warning,true);assert.equal(lifecycleRisk({...r,requests:0}).warning,false);assert.equal(lifecycleRisk({...r,fits:false}).warning,false);});
test('lifecycle defaults, overrides and memory stress survive shared URLs',()=>{const s=normalize({...defaults,modelRefresh:6,hardwareRefresh:24,nextModelGrowth:1.5});const copy=decodeState(encodeState(s));assert.equal(copy.modelRefresh,6);assert.equal(copy.hardwareRefresh,24);assert.equal(copy.nextModelGrowth,1.5);const bounded=normalize({...s,modelRefresh:0,hardwareRefresh:Infinity,nextModelGrowth:0});assert.equal(bounded.modelRefresh,1);assert.equal(bounded.hardwareRefresh,defaults.hardwareRefresh);assert.equal(bounded.nextModelGrowth,1);});
test('cash remaining at first lifecycle review excludes resale',async()=>{const {lifecycleRisk}=await import('../src/planner.js');const r=calculate(defaults);const risk=lifecycleRisk({...r,capital:1000,cloud:150,recurring:50,rentalMonthly:250,s:{...r.s,modelRefresh:3,hardwareRefresh:12,rentalSetup:100,resale:90}});assert.equal(risk.unrecoveredVsApi,700);assert.equal(risk.unrecoveredVsRent,300);});

test('factory targets continuous high-volume autonomous teams and preserves capacity limits',()=>{const s=applyWorkload({...defaults,users:1},'swe-factory');const r=calculate(s);assert.equal(s.scaleMode,1);assert.equal(s.days,30);assert.equal(s.hours,24);assert.equal(s.rentalHours,720);assert.equal(s.efficiency,95);assert.equal(s.rentalEfficiency,95);assert.equal(r.batch,4);assert.equal(r.requests,172800);assert.equal(r.requests*(s.input+s.output),5529600000);assert.ok(r.contextOk);assert.ok(r.localRequests<=r.capacity);assert.ok(r.overflow>0);assert.equal(r.capacity,r.rentalCapacity);});
test('switching from factory restores AI-assisted business schedule and concurrency',()=>{const s=applyWorkload(applyWorkload({...defaults,users:3},'swe-factory'),'swe');assert.equal(s.scaleMode,0);assert.equal(s.days,21.67);assert.equal(s.hours,8);assert.equal(s.rentalHours,173.36);assert.equal(s.activity,40);assert.equal(s.efficiency,70);assert.equal(s.users,3);});
test('factory and custom autonomous scale survive shared URLs',()=>{const s=optimize(applyWorkload({...defaults,users:2},'swe-factory'));const linked=decodeState(encodeState(s));assert.equal(linked.workload,'swe-factory');assert.equal(linked.scaleMode,1);assert.equal(linked.rentalHours,720);assert.equal(linked.users,2);assert.equal(normalize({...linked,workload:'custom'}).scaleMode,1);assert.ok(calculate(linked).fits);});
test('complete system presets preserve GPU memory limits and matched rental capacity',()=>{
 for(const h of hardware){
  assert.ok(h.package && h.price>0 && h.rental>0,h.id);
  const s=hardwareState({...defaults,matchHardware:1,rentalHours:defaults.days*defaults.hours},h);
  const r=calculate(s);
  assert.equal(r.capacity,r.rentalCapacity,h.id);
 }
 for(const [id,available] of [['strix-framework-64',48],['strix-framework-128',96],['strix-hp-128',96],['5080-pc',14],['5090-single',29]]){
  const h=hardware.find(h=>h.id===id);
  assert.equal(calculate(hardwareState(defaults,h)).available,available);
  assert.equal(decodeState(encodeState(hardwareState(defaults,h))).hardware,id);
 }
});
