import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {parse} from 'acorn';
import {datasets,data} from '../src/data/registry.js';
export const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
export const fileFor=id=>id.replace(/[A-Z]/g,x=>'-'+x.toLowerCase())+'.js';
export function leaves(value,prefix=''){
 if(value!==null&&typeof value==='object'&&Object.keys(value).length)return Object.entries(value).flatMap(([key,v])=>leaves(v,prefix?`${prefix}.${key}`:key));
 return [[prefix,value]];
}
export function walk(node,visit){if(!node||typeof node!=='object')return;visit(node);for(const [key,value] of Object.entries(node)){if(key==='start'||key==='end')continue;if(Array.isArray(value))value.forEach(x=>walk(x,visit));else if(value&&typeof value==='object')walk(value,visit);}}
export function literals(source){const out=[];walk(parse(source,{ecmaVersion:'latest',sourceType:'module'}),n=>{if(n.type==='Literal'&&typeof n.value==='number')out.push(n.value);});return [...new Set(out)].sort((a,b)=>a-b);}
const escape=v=>String(v).replaceAll('|','\\|').replaceAll('\n',' ');
export function inventory(){
 let text='# Maintained data inventory\n\nGenerated by `npm run data:inventory`. Edit the adjacent data files, then regenerate; do not edit this inventory by hand.\n\nAll paths below are relative to each file’s `values` object. Every scalar, null and empty collection is listed, including raw endpoint evidence that is not used in calculations. Metadata fields (`kind`, `reviewed`, `frequency`, `source`, `how`) apply to every field in their file: change `reviewed` only after an actual source review. A refactor is not a new review.\n\nSee [README.md](README.md) for the mandatory update workflow, units, source-of-truth relationships, user-input lifecycle and field interpretation. Null means unknown/unset, never a free price. Browser overrides and shared links are user inputs, not maintained catalog records.\n\n';
 for(const [id,d] of Object.entries(datasets)){
  const m=d.maintenance;const values=leaves(d.values);
  text+=`## [${fileFor(id)}](${fileFor(id)})\n\nType: **${m.kind}**. Recorded review: **${m.reviewed}**.\n\n**Frequency:** ${m.frequency}\n\n**Source:** ${m.source}\n\n**How to update each field:** ${m.how}\n\n| Field | Current value |\n|---|---|\n`;
  for(const [key,value] of values)text+=`| \`${key||'(collection)'}\` | ${escape(JSON.stringify(value))} |\n`;
  text+='\n';
 }
 return text;
}
export async function validate(){
 const errors=[];
 const dataFiles=await fs.readdir(path.join(root,'src/data'));
 const files=dataFiles.filter(f=>f.endsWith('.js'));
 for(const file of dataFiles)if(!file.endsWith('.js')&&!['README.md','INVENTORY.md'].includes(file))errors.push(`Unregistered data artifact: ${file}`);
 const expected=['index.js','registry.js',...Object.keys(datasets).map(fileFor)].sort();
 if(JSON.stringify(files.sort())!==JSON.stringify(expected))errors.push('Every data file must be registered; no unregistered JavaScript data files allowed.');
 for(const [id,d] of Object.entries(datasets)){
  const filename=fileFor(id),source=await fs.readFile(path.join(root,'src/data',filename),'utf8');
  const tree=parse(source,{ecmaVersion:'latest',sourceType:'module'});
  if(tree.body.length!==1||tree.body[0].type!=='ExportDefaultDeclaration'||tree.body[0].declaration.type!=='ObjectExpression')errors.push(`${filename}: data must be a single declarative default object export`);
  walk(tree,n=>{if(['CallExpression','NewExpression','ImportDeclaration','SpreadElement','FunctionExpression','ArrowFunctionExpression','TemplateLiteral'].includes(n.type))errors.push(`${filename}: executable/derived data is forbidden (${n.type})`);});
  for(const field of ['kind','reviewed','frequency','source','how'])if(typeof d.maintenance?.[field]!=='string'||!d.maintenance[field].trim())errors.push(`${filename}: missing maintenance.${field}`);
  if(!/^\d{4}-\d{2}-\d{2}$/.test(d.maintenance.reviewed))errors.push(`${filename}: invalid review date`);
  for(const field of ['frequency','source','how'])if(!source.slice(0,source.indexOf('*/')).includes(d.maintenance[field]))errors.push(`${filename}: top comment must match maintenance.${field}`);
  for(const [field,value] of leaves(d.values))if(typeof value==='number'&&!Number.isFinite(value))errors.push(`${filename}:${field}: nonfinite value`);
 }
 for(const [id,m] of Object.entries(data.models)){
  if(m.id||['input','output','cached','provider','providerTag','quantization','context','maxInput','maxOutput','planningMemoryGB'].some(k=>k in m))errors.push(`${id}: duplicated endpoint/memory field`);
  if(!m.source?.startsWith('https://')||!m.apiModel||!m.endpoint?.tag||!m.endpoint?.provider_name)errors.push(`${id}: missing endpoint provenance`);
  for(const k of ['prompt','completion'])if(m.endpoint?.pricing?.[k]==null||!Number.isFinite(Number(m.endpoint.pricing[k]))||Number(m.endpoint.pricing[k])<0)errors.push(`${id}: invalid ${k} price`);
  if(!(m.endpoint?.context_length>0)||!(m.endpoint?.max_completion_tokens>0))errors.push(`${id}: missing endpoint limits`);
  if(!(data.inferenceMemory[id]>0)||!data.trainingModels[id])errors.push(`${id}: missing memory/training profile`);
 }
 for(const [id,r] of Object.entries(data.rentals)){
  if(['hourly','memory','source','billingSource'].some(k=>k in r))errors.push(`${id}: derived rental data must not be duplicated`);
  if(!(r.perGpu>=0)||!(r.gpus>0)||!(r.vram>0))errors.push(`${id}: invalid rental economics/resources`);
 }
 for(const [id,w] of Object.entries(data.workloads))for(const model of w.models)if(!data.models[model])errors.push(`${id}: unknown shortlist model ${model}`);
 for(const [id,h] of Object.entries(data.hardware)){
  for(const key of ['sourceRef','priceSourceRef','runtimeSourceRef'])if(h[key]&&!data.sources[h[key]])errors.push(`${id}: invalid ${key}`);
  if(h.baseHardwareId&&(!data.hardware[h.baseHardwareId]||data.hardware[h.baseHardwareId].baseHardwareId||h.memory!=null||!(h.nodes>0)))errors.push(`${id}: invalid or duplicated cluster memory`);
  for(const text of [h.name,h.package])for(const match of text.matchAll(/\{(\w+)\}/g))if(![...Object.keys(h),'baseMemory'].includes(match[1]))errors.push(`${id}: unknown text template ${match[1]}`);
  if(h.price!=null&&!h.priceSourceRef)errors.push(`${id}: published price requires provenance`);
 }
 for(const [id,a] of Object.entries(data.purchaseAllowances))if(typeof a==='object'&&(!data.hardware[a.baseHardwareId]||!(a.nodes>0)||!(a.extras>=0)))errors.push(`${id}: invalid cluster allowance`);
 for(const r of data.frontier.referenceModels)for(const key of Object.keys(data.frontier.referencePolicy))if(key in r)errors.push(`${r.id}: duplicated reference ${key}`);
 for(const [id,t] of Object.entries(data.trainingSystems)){
  if(t.rentalId&&(!data.rentals[t.rentalId]||['hourly','vram','gpus'].some(k=>k in t)))errors.push(`${id}: invalid or duplicated rental reference`);
  if(t.hardwareId&&(!data.hardware[t.hardwareId]||['price','vram','gpus','source'].some(k=>k in t)))errors.push(`${id}: invalid or duplicated hardware reference`);
 }
 for(const r of data.reviewedConfigurations){for(const key of ['mode','kind','hardwareId','scope','evidenceURL','modelRevision','runtimeVersions','completeSystem','reproduction','result','status','reviewedOn','expiresOn'])if(!r[key])errors.push(`Reviewed configuration missing ${key}`);}
 for(const helper of ['index.js','registry.js'])errors.push(...boundaryViolations(await fs.readFile(path.join(root,'src/data',helper),'utf8'),'data/'+helper,{reason:'Unit conversion to per-million tokens and two-decimal currency rounding only',values:[2,1000000]}));
 const allowed=JSON.parse(await fs.readFile(path.join(root,'scripts/code-constants.json'),'utf8'));
 async function applicationFiles(dir,prefix=''){
  const found=[];
  for(const entry of await fs.readdir(dir,{withFileTypes:true})){
   if(!prefix&&entry.name==='data')continue;
   const name=prefix+entry.name;
   if(entry.isDirectory())found.push(...await applicationFiles(path.join(dir,entry.name),name+'/'));
   else if(entry.name.endsWith('.js'))found.push(name);
   else if(/\.(json|csv|tsv|ya?ml)$/.test(entry.name))errors.push(`${name}: data artifacts must live in src/data/`);
  }
  return found;
 }
 for(const file of await applicationFiles(path.join(root,'src'))){
  const source=await fs.readFile(path.join(root,'src',file),'utf8');
  errors.push(...boundaryViolations(source,file,allowed[file]));
 }
 if(errors.length)throw new Error(errors.join('\n'));
 return {datasets:Object.keys(datasets).length,fields:Object.values(datasets).reduce((n,d)=>n+leaves(d.values).length,0)};
}

// Pure boundary checker also used with hostile fixtures in regression tests.
export function boundaryViolations(source,file,allowance){
 const errors=[];
 for(const number of literals(source))if(!allowance?.values.includes(number))errors.push(`${file}: numeric literal ${number} is not an approved algorithm/UI constant. Put maintained values in src/data/.`);
 if(!allowance?.reason)errors.push(`${file}: missing code-constant classification`);
 walk(parse(source,{ecmaVersion:'latest',sourceType:'module'}),n=>{
  const value=n.type==='Literal'&&typeof n.value==='string'?n.value:n.type==='TemplateElement'?n.value.cooked:'';
  if(/https?:\/\/|\b20\d{2}-(?:0[1-9]|1[0-2])(?:-\d\d)?\b/.test(value))errors.push(`${file}: source URLs and snapshot dates must live in src/data/`);
 });
 return errors;
}
