import {planning,assumptionNotes} from './planning.js?v=14';
import {models,hardware,rentals,workloads,defaults,reviewed} from './catalog.js?v=14';
import {calculate,normalize,optimize,suggestRental,clearMeasurements} from './engine.js?v=14';
import {encodeState,decodeState} from './sharing.js?v=14';
import {tariffSource,countySource,ridersCents} from './energy.js?v=14';
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const n=(x,d=1)=>typeof x==='number'&&Number.isFinite(x)?x.toLocaleString('en-US',{maximumFractionDigits:d}):'Not verified';
const money=x=>typeof x==='number'&&Number.isFinite(x)?new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(x):'Not verified';
const link=(url,label)=>`<a href="${esc(url)}" target="_blank" rel="noreferrer">${esc(label)} ↗</a>`;
let state=optimize(defaults),legacy=false;
try{const saved=JSON.parse(localStorage.getItem('inference-ledger-v2'));if(saved)state=normalize(saved);else legacy=!!localStorage.getItem('inference-ledger-v1');}catch{}
const linked=decodeState(location.search);if(linked)state=linked;else if(new URLSearchParams(location.search).has('scenario'))legacy=true;
state=planning(state);
const field=(key,label,type='number')=>`<label>${label}${key==='users'?'':` <small class="assumption-tag">${state.overrides.split(',').includes(key)?'Your override':'Automatic default'}</small>`}<input name="${key}" type="${type}" ${type==='number'?'min="0" step="any"':''} value="${esc(state[key])}" placeholder="${type==='number'?'Not verified':'Source / measurement reference'}"></label>`;
const select=(key,label,opts)=>`<label>${label}<select name="${key}">${opts.map(([id,name])=>`<option value="${esc(id)}" ${String(id)===String(state[key])?'selected':''}>${esc(name)}</option>`).join('')}</select></label>`;
const detail=(label,content)=>`<details class="form-details"><summary>${label}</summary><div class="disclosure-body">${content}</div></details>`;
const group=(no,title,content)=>`<fieldset><legend><span>${no}</span>${title}</legend>${content}</fieldset>`;
function controls(){
 const h=hardware.find(h=>h.id===state.hardware),m=models.find(m=>m.id===state.model),r=rentals.find(r=>r.id===state.rental),factory=state.workload==='swe-factory';
 const open=[...$('controls').querySelectorAll('details[open]')].map(d=>d.querySelector('summary').textContent);
 const usage=select('workload','What work will AI perform?',workloads)+field('users',factory?'Autonomous teams':'People using AI')+`<p class="field-note">${factory?'24/7 operation with no human in the loop. High-volume agent activity is estimated automatically.':'9–5, Monday–Friday. Operating days are counted from the calendar; public holidays are not removed.'} Usage and concurrency are filled automatically from an editable planning template.</p>`+detail('Advanced: usage assumptions',`<p class="field-note">Defaults are planning assumptions, not universal averages. Replace them with a representative pilot when available. Include reasoning tokens and every agent call.</p><div class="fields">${field('start','Starting month','month')}${field('calls',factory?'Calls / team / operating day':'Calls / person / operating day')}${field('input','Mean input tokens / call')}${field('output','Mean output tokens / call')}${field('concurrency','Estimated peak concurrent calls')}${field('usageSource','Workload assumption / evidence','text')}</div>`);
 const model=select('model','Model used in all three paths',models.map(m=>[m.id,m.name]))+`<p class="field-note">${link(m.source,'Model card')} · ${link(m.apiSource,'API price evidence')}<br>${esc(m.provider)} · ${esc(m.quantization)}<br>${money(m.input)} input / ${money(m.output)} output per million tokens.</p>`+detail('Advanced: API and model evidence',`<p class="field-note">Endpoint ${esc(m.providerTag)}; context ${n(m.context,0)}, maximum output ${n(m.maxOutput,0)}. Prices checked ${reviewed}. No cache savings are assumed. Routing to another provider can change rates and precision. Verify availability, quality and rate limits.</p><p class="field-note">Task suggestions are editorial, not a universal score ranking. Model cards contain the original evaluation results and deployment instructions. Performance estimates are planning proxies; advanced settings can replace them with benchmarks.</p>${select('autoModel','On task change',[[1,'Use task shortlist suggestion'],[0,'Keep this model']])}`);
 const system=select('hardware','Complete system to buy',hardware.map(h=>[h.id,h.name]))+`<p class="field-note">${money(state.quote)}${h.price===null?' · planning allowance':' · published price / advanced override'}<br>${h.memory} GB ${esc(h.kind)} · ${link(h.source,'Specifications')}</p>`+select('rental','Real cloud instance to rent',rentals.map(r=>[r.id,`${r.name} · ${money(r.hourly)}/hour`]))+`<p class="field-note">${esc(r.package)} · ${r.memory} GB GPU memory.<br>${link(r.source,'Instance and price evidence')} · ${r.gpus} GPU(s) × ${money(r.perGpu)}/GPU-hour.<br>Suggested by memory and published rate; speed and runtime support are not assumed equal.</p>`;
 const bench=detail('Benchmarks & compatibility',`<p class="field-note">Measure completed requests/hour for this exact model, precision, context, token mix and concurrency, including prefill and decode. Automatic values below are labeled proxies; replace them with separate local and rental results. Enter 0 for measured inability to serve. Simple changes recalculate estimates. Advanced overrides are kept until you restore automatic assumptions.</p><div class="fields">${field('localRph','Purchase system: estimated calls/hour')}${field('localAvailable','Purchase: usable model memory GB')}${field('localMemory','Purchase: estimated runtime memory GB')}${field('localRuntime','Purchase runtime & precision','text')}${field('localEvidence','Purchase benchmark reference','text')}${field('rentalRph','Rental: estimated calls/hour')}${field('rentalAvailable','Rental: usable model memory GB')}${field('rentalMemory','Rental: estimated runtime memory GB')}${field('rentalRuntime','Rental runtime & precision','text')}${field('rentalEvidence','Rental benchmark reference','text')}</div>`);
 const quotes=detail('Quotes, fees & complete build',`<p class="field-note">${esc(h.package)} ${h.runtimeSource?link(h.runtimeSource,'Runtime documentation'):''}</p><p class="field-note">${h.priceSource?link(h.priceSource,'Published purchase price')+' · '+esc(h.priceKind):'No published full-system price verified; the filled amount is a planning allowance.'} A quoted replacement price takes priority only when a source is supplied. Include shipping, taxes, networking, support and installation; avoid double counting.</p><div class="fields">${field('quote','Quoted equipment price ($)')}${field('quoteSource','Quote reference / date','text')}${field('buildDetails','Complete quoted build (if configurable)','text')}${field('localSetup','Purchase: one-time extras ($)')}${field('localExtras','Purchase: monthly support, tax & other costs ($)')}${field('rentalSetup','Rental: one-time fees ($)')}${field('rentalExtras','Rental: monthly storage, tax & other fees ($)')}${field('apiExtras','API: monthly platform, credit-purchase & other fees ($)')}${field('costSource','Fee / tax evidence','text')}</div><p class="field-note">Clearing an advanced field restores its automatic assumption. ${link(r.billingSource,'Rental billing terms')}. Rental hours follow the operating schedule; the entire reserved instance is billed. Stopping/restarting and retained storage must be operationally feasible.</p>`);
 const electricity=detail('Loudoun power & cooling',`<p class="field-note"><strong>Dominion Energy Virginia — business.</strong> GS-1 is for eligible small-business accounts. Confirm the bill schedule and whole-site demand; large offices may use a different tariff.</p>${select('tariff','Electricity calculation',[['gs1','Published GS-1 tariff + Loudoun tax'],['bill','Use estimated / bill-based all-in rate']])}<div class="fields">${field('itKwh','Estimated IT energy / month (kWh)')}${field('coolingKwh','Estimated extra cooling / month (kWh)')}${field('energySource','Energy measurement / HVAC report','text')}${field('baselineKwh','Existing site usage / month (kWh)')}${field('peakKw','Whole-site peak including AI (kW)')}${select('tariffConfirmed','GS-1 verified on your bill?',[[0,'Not yet verified'],[1,'Yes — standard GS-1, no special minimum']])}${select('localTax','County utility tax jurisdiction',[[1,'Loudoun County utility tax applies'],[0,'Town or other jurisdiction — use bill rate']])}${field('billRate','All-in incremental $/kWh')}${field('billSource','Dominion bill / tariff reference','text')}</div><p class="field-note">Cooling uses the same tariff as IT. Default energy and cooling values are explicitly labeled planning assumptions. Monthly kWh inputs are held as your measured budget; remeasure when workload changes. Existing customer charges cancel in incremental costs; new meters and demand/minimum charges belong in documented extras.</p><p class="field-note">${link(tariffSource,'Dominion tariff (September 2026)')} · ${link(countySource,'Loudoun taxes')}. Standard riders, deferred fuel, sales/use surcharge, consumption tax and county utility-tax cap are included. Tariff assumptions exclude special contracts/exemptions and do not apply at 30 kW or above. Use an all-in bill rate for other business schedules.</p>`);
 const future=detail('Contractual price changes & lifecycle',`<p class="field-note">Current rates are held constant unless you provide a documented discount or contract change. An observed historical price decline is not a forecast. Enter 0% purchase discount if your quote is already discounted. Default review intervals are planning policy assumptions, not industry guarantees.</p><div class="fields">${field('purchaseDiscount','Documented purchase discount (%)')}${field('rentalDecline','Contractual rental reduction / year (%)')}${field('apiDecline','Contractual API reduction / year (%)')}${field('priceEvidence','Discount / contract evidence','text')}${field('modelRefresh','Your model review interval (months)')}${field('hardwareRefresh','Your hardware review interval (months)')}${field('lifecycleSource','Review policy / release evidence','text')}</div>`);
 $('controls').innerHTML=group('01','Task & scale',usage)+group('02','Model & API',model)+group('03','Buy & rent systems',system+detail('Advanced: evidence & costs','<button type="button" id="restore-assumptions">Restore automatic assumptions</button>'+select('autoHardware','After task or model changes',[[1,'Suggest a system that fits'],[0,'Keep selected purchase system']])+select('autoRental','After system changes',[[1,'Suggest comparable memory rental'],[0,'Keep selected rental']])+bench+quotes+electricity+future));
 for(const d of $('controls').querySelectorAll('details'))d.open=open.includes(d.querySelector('summary').textContent);
}
function render(){
 const r=calculate(state),first=r.first,last=r.last,suggestion=suggestRental(state);
 $('migration').hidden=!legacy;
 $('summary').innerHTML=`<section class="recommendation"><div class="eyebrow">PLANNING ESTIMATE · EDITABLE ASSUMPTIONS</div><h2>${r.ready?(r.payback!==null?`Buying recovers its cost in ${n(r.payback)} months`:`${r.last.api<=r.last.rent?'Pay per use':'Renting'} looks less expensive than buying`):'Published prices. Measurements still needed.'}</h2><p>${r.ready?'Estimated from sourced rates and the assumptions below. Payback must remain ahead of both alternatives throughout the 120-month calculation.':'Prices and specifications have source links. Missing workload, performance or operating costs prevent a responsible buy/rent recommendation.'}</p><details><summary>Assumptions behind this estimate</summary><ul>${assumptionNotes(state).map(t=>`<li>${esc(t)}</li>`).join('')}</ul><p>Advanced overrides: ${esc(state.overrides||'None — automatic defaults')}</p></details>${r.issues.length?`<details><summary>What is missing? (${r.issues.length})</summary><ul>${r.issues.map(t=>`<li>${esc(t)}</li>`).join('')}</ul></details>`:''}</section>${r.lifecycle?'<div class="lifecycle-notice"><span>Estimated payback exceeds the review window.</span><button type="button" id="lifecycle-open">View details</button></div>':''}<div class="metrics">${[['Buy system',r.purchase,'Published price or labeled planning allowance'],['Rent instance',r.r.hourly,'USD/hour for the entire instance'],['API usage',first.apiUsage,'Monthly tokens only; excludes platform fees']].map(([title,value,desc])=>`<article class="metric"><div class="eyebrow">${title}</div><h2>${money(value)}</h2><p>${desc}</p></article>`).join('')}</div><div class="plain-assumptions"><p><strong>This workload:</strong> ${n(first.requests,0)} requests/month · ${r.firstSchedule.days} operating days · ${first.hours} operating hours · ${n(state.concurrency,0)} concurrent calls.</p><p><strong>Comparison:</strong> ${esc(r.h.name)} versus ${esc(r.r.name)}. ${r.h.memory} GB ${esc(r.h.kind)} versus ${r.r.memory} GB GPU memory. These systems use different architectures; no speed, precision or quality parity is claimed.</p>${!suggestion?'<p>No catalog rental has enough installed GPU memory to match the selected memory target. The selected rental is not represented as a match.</p>':''}<p class="caption">Checked ${reviewed}; stock, region availability and negotiated prices can change. User-entered evidence is identified as user supplied, not independently verified by this site.</p></div>`;
 const row=(label,...vals)=>`<tr><th>${label}</th>${vals.map(v=>`<td>${v}</td>`).join('')}</tr>`;
 $('comparison').innerHTML=`<h2>Same workload, actual offerings</h2><div class="table-wrap"><table><thead><tr><th>Cost or evidence</th><th>Buy</th><th>Rent</th><th>API</th></tr></thead><tbody>${row('Configuration',esc(r.h.name),esc(r.r.name),esc(r.m.provider))}${row('Runtime / precision',esc(state.localRuntime)||'Not verified',esc(state.rentalRuntime)||'Not verified',esc(r.m.quantization))}${row('Month-one total',money(first.buyMonthly),money(first.rentMonthly),money(first.apiMonthly))}${row(`${r.months}-month total`,money(last.buy),money(last.rent),money(last.api))}${row('Reserved compute / month','—',money(first.compute),'—')}${row('Capacity (calls/month)',n(first.localCapacity,0),n(first.rentalCapacity,0),'Rate limits not verified')}${row('Overflow API charges',money(first.localOverflow),money(first.rentalOverflow),'Included')}${row('IT electricity',money(r.power?.it),'Provider electricity included','Included')}${row('Extra cooling',money(r.power?.cooling),'Provider cooling included','Included')}${row('Cash payback vs API',r.paybackApi===null?'Not established':n(r.paybackApi)+' months','—','—')}${row('Cash payback vs rental',r.paybackRent===null?'Not established':n(r.paybackRent)+' months','—','—')}</tbody></table></div><p class="caption">Overflow uses the same model’s listed API endpoint. API capacity, quantization quality and service-level requirements still need a pilot. No residual value, hardware replacements, demand growth or speculative future prices are included.</p>`;
 $('capacity').innerHTML=`<h2>Capacity evidence</h2><p>Purchase: ${r.localReady?'Entered estimate fits the memory budget; validate with a benchmark.':'Not verified.'} Rental: ${r.rentalReady?'Entered estimate fits the memory budget; validate with a benchmark.':'Not verified.'}</p><p>Memory is checked against measured peak use and usable memory for each runtime. A sum of card or node memory does not establish sharding support. Benchmark evidence must include the exact model, precision, context, concurrency and deployment recipe.</p>`;
 $('hardware-table').innerHTML=hardware.map(h=>`<tr><td><button type="button" data-hardware="${h.id}">${esc(h.name)}</button></td><td>${h.memory} GB ${esc(h.kind)}</td><td>${money(h.price??planning({...defaults,hardware:h.id,autoHardware:0}).quote)}${h.price===null?' (assumed)':' (published)'}</td><td>${link(h.source,'Specs')}${h.priceSource?' · '+link(h.priceSource,'Price'):''}</td><td>Planning proxy; benchmark before buying</td></tr>`).join('');
 $('horizon').textContent=`${r.months} months · automatic`;
 draw(r);
 $('lifecycle-content').innerHTML=`<p>Model review: ${n(state.modelRefresh)} months. Hardware review: ${n(state.hardwareRefresh)} months.</p><p>${esc(state.lifecycleSource)}</p><p>This is your review policy, not an industry obsolescence forecast. No future model size or replacement cost is invented.</p>`;
 const isDefault=encodeState(state)===encodeState(planning(defaults));
 history.replaceState(null,'',location.pathname+(isDefault?'':'?'+encodeState(state)));
 try{localStorage.setItem('inference-ledger-v2',JSON.stringify(state));}catch{}
}
function draw(r){
 const valid=[['buy','#206451'],['rent','#687281'],['api','#7960a4']].filter(([key])=>r.last[key]!==null);
 if(!valid.length){$('chart').innerHTML='<p class="empty-chart">Add documented workload and cost inputs to see the long view.<br>Unknown values are never plotted as zero.</p>';$('payback-note').textContent='Payback cannot be calculated from price alone.';return;}
 const W=760,H=280,p=45,max=Math.max(1,...valid.map(([k])=>Math.max(...r.rows.slice(0,r.months+1).map(row=>row[k]))));
 const x=m=>p+m/r.months*(W-2*p),y=v=>H-p-v/max*(H-2*p);
 let svg=`<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="Cumulative cost projections based on sourced rates and editable assumptions">`;
 for(let j=0;j<=4;j++){const v=max*j/4;svg+=`<line x1="${p}" x2="${W-p}" y1="${y(v)}" y2="${y(v)}" stroke="#ddd"/><text x="${p-5}" y="${y(v)-5}" font-size="10">${money(v)}</text>`;}
 for(const [k,color] of valid){svg+=`<path d="${r.rows.slice(0,r.months+1).map((row,i)=>`${i?'L':'M'}${x(i)},${y(row[k])}`).join(' ')}" fill="none" stroke="${color}" stroke-width="3"/>`;}
 if(r.payback!==null&&r.payback<=r.months)svg+=`<line x1="${x(r.payback)}" x2="${x(r.payback)}" y1="25" y2="${H-p}" stroke="#206451" stroke-dasharray="5 5"/><text x="${Math.min(W-150,x(r.payback)+5)}" y="20" font-size="12">Payback ${n(r.payback)} mo</text>`;
 svg+=`<text x="${p}" y="${H-12}" font-size="12">Today</text><text x="${W-100}" y="${H-12}" font-size="12">Month ${r.months}</text></svg>`;
 $('chart').innerHTML=svg;$('payback-note').textContent=r.ready?(r.payback===null?'No sustained payback against both alternatives through month 120. Showing a five-year view.':'The line marks the later payback against API or renting. The view extends beyond it, capped at ten years.'):'Partial projection only: paths with missing evidence are omitted. No purchase recommendation is made.';
}
const modelSuggestion=task=>['swe','swe-factory','security'].includes(task)?'qwen80':['research','bizdev'].includes(task)?'minimax':'oss120';
$('controls').addEventListener('submit',e=>e.preventDefault());
$('controls').addEventListener('change',e=>{
 const el=e.target,k=el.name;if(!(k in defaults))return;
 const value=el.type==='number'?(el.value===''?null:Number(el.value)):el.value;
 state=normalize({...state,[k]:value});
 const simple=['workload','users','model','hardware','rental','autoModel','autoHardware','autoRental'];
 const overrides=new Set(state.overrides.split(',').filter(Boolean));
 if(!simple.includes(k)){if(value===null||value==='')overrides.delete(k);else overrides.add(k);}
 state.overrides=[...overrides].join(',');
 if(k==='workload'&&state.autoModel)state.model=modelSuggestion(state.workload);
 if(k==='model')state.autoModel=0;
 if(k==='hardware')state.autoHardware=0;
 if(k==='rental')state.autoRental=0;
 if(k==='autoModel'&&state.autoModel)state.model=modelSuggestion(state.workload);
 state=planning(state);
 controls();render();
});
$('controls').addEventListener('click',e=>{if(e.target.id==='restore-assumptions'){state=planning({...state,overrides:''});controls();render();}});
$('hardware-table').addEventListener('click',e=>{const b=e.target.closest('[data-hardware]');if(!b)return;const el=$('controls').querySelector('[name=hardware]');el.value=b.dataset.hardware;el.dispatchEvent(new Event('change',{bubbles:true}));});
$('reset').addEventListener('click',()=>{state=planning(defaults);legacy=false;try{localStorage.removeItem('inference-ledger-v1');localStorage.removeItem('inference-ledger-v2');}catch{}$('controls').innerHTML='';controls();render();});
$('share').addEventListener('click',async()=>{try{await navigator.clipboard.writeText(location.origin+location.pathname+'?'+encodeState(state));$('share-status').textContent='Configuration link copied.';}catch{$('share-status').textContent='Copy the address bar URL.';}});
$('export').addEventListener('click',()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify({schemaVersion:7,checked:reviewed,inputs:state,result:calculate(state)},null,2)],{type:'application/json'}));a.download='inference-ledger-evidence.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);});
$('summary').addEventListener('click',e=>{if(e.target.id==='lifecycle-open')$('lifecycle-dialog').showModal();});
$('lifecycle-close').addEventListener('click',()=>$('lifecycle-dialog').close());
$('lifecycle-dialog').addEventListener('click',e=>{if(e.target===e.currentTarget){const b=e.currentTarget.getBoundingClientRect();if(e.clientX<b.left||e.clientX>b.right||e.clientY<b.top||e.clientY>b.bottom)e.currentTarget.close();}});
addEventListener('popstate',()=>{state=planning(decodeState(location.search)??defaults);controls();render();});
$('methodology').innerHTML='<p>Monthly requests = people or teams × assumed or measured calls per day × calendar operating days. Capacity = estimated or measured completed requests/hour × operating hours, separately for each system. Overflow is charged at the selected API endpoint’s uncached token prices. Default throughput and memory estimates are planning proxies, not compatibility certifications.</p><p>Payback compares cumulative cash flows for 120 months, excluding resale. The later sustained crossing against both alternatives is used. A five-year display without a crossing is a presentation window, not an assumed useful life. Price reductions require documented contract terms. Existing tariff rates are held constant and summer/winter tiers are applied; future rates are unknown.</p>';
$('sources').innerHTML=`<p>Checked ${reviewed}. Every catalog fact links to a primary vendor/provider source. Blank prices mean no verified complete-system quote. Specifications do not imply tested model support. Task, performance and cost assumptions are provided automatically and labeled separately from sourced catalog facts.</p><h3>API endpoints</h3>${models.map(m=>`<p>${esc(m.name)} · ${esc(m.provider)} · ${link(m.apiSource,'Rates & endpoint')} · ${link(m.source,'Model card')}</p>`).join('')}<h3>Purchase systems</h3>${hardware.map(h=>`<p>${esc(h.name)} · ${link(h.source,'Specs')}${h.priceSource?' · '+link(h.priceSource,'Price'):''}<br>${esc(h.package)}</p>`).join('')}<h3>Rental instances</h3><p>${link('https://lambda.ai/instances','Lambda on-demand instance table')} · ${link('https://docs.lambda.ai/public-cloud/on-demand/billing/','Billing terms')}. Multi-GPU prices multiply the published per-GPU price by the actual GPU count. Region availability and sufficient serving capacity must be checked separately.</p><h3>Dominion GS-1 — Loudoun</h3><p>${link(tariffSource,'Filed tariff')} · ${link(countySource,'County taxes')}. Rates effective as of September 2026. GS-1 base rates: first 1,400 kWh distribution 2.5525¢ + generation 3.0788¢; above that, distribution 1.8928¢ + generation 4.1350¢ June–September or 1.9886¢ October–May; transmission 0.582¢/kWh.</p><p>Riders (¢/kWh): ${Object.entries(ridersCents).map(([k,v])=>`${k} ${v}`).join('; ')}. Sales/use surcharge $0.000847/kWh. Consumption tax tiers $0.001565 / $0.001055 / $0.000845 at 2,500 and 50,000 kWh. County commercial tax: $0.92 + $0.005393/kWh, capped at $72/account/month. Incremental cost subtracts the existing site bill and applies cooling after IT usage. Fixed existing-meter charges cancel. No special contracts, exemptions or data-center tax classifications are modeled.</p>`;
controls();render();
