import {models,hardware,defaults,benchmarkSource,workloads,applyWorkload} from './catalog.js?v=3';
import {calculate,normalize,combinedPayback} from './engine.js?v=4';
const $=id=>document.getElementById(id);
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);
const num=(n,d=0)=>Number.isFinite(n)?n.toLocaleString('en-US',{maximumFractionDigits:d}):'—';
let state={...defaults};
try {const saved=JSON.parse(localStorage.getItem('inference-ledger-v1')); if(saved)state=normalize(saved);else state=applyWorkload(state,'chat');}catch{}
const field=(key,label,step=1,max='')=>`<label>${label}<input name="${key}" type="number" min="0" ${max?`max="${max}"`:''} step="${step}" value="${state[key]}" required></label>`;
const select=(key,label,options)=>`<label>${label}<select name="${key}">${options.map(([v,t])=>`<option value="${v}" ${String(state[key])===String(v)?'selected':''}>${t}</option>`).join('')}</select></label>`;
const group=(n,title,content)=>`<fieldset><legend><span>${n}</span>${title}</legend>${content}</fieldset>`;
const disclosure=(title,body)=>`<details class="form-details"><summary>${title}</summary><div class="disclosure-body">${body}</div></details>`;
function controls(){
const workload=select('workload','What will your team use AI for?',[['custom','Custom usage'],...workloads.map(w=>[w.id,w.name])])+field('users','How many people will use it?')+field('months','Compare costs over how many months?',1,120)+`<p class="field-note">Templates assume an 8-hour day, Monday–Friday. We estimate the amount of work and how many people use AI at once. You can adjust these assumptions below.</p><p id="workload-estimate" class="field-note"></p>`;
const prices=`<p class="field-note">Starting prices are examples, not vendor quotes. Replace them with your company’s quotes before making a purchase.</p>`+disclosure('Buying: purchase & running costs',`<div class="fields">${field('price','Purchase price ($)')}${field('setup','Installation ($)')}${field('maintenance','Monthly support ($)')}${field('electricity','Electricity ($/kWh)',0.01)}${field('resale','Resale value (%)',1,100)}</div>`)+disclosure('Renting: provider charges',`<div class="fields">${field('rental','System rental ($/hour)',0.01)}${field('rentalHours','Paid hours each month',0.01,720)}${field('rentalExtra','Other monthly fees ($)')}${field('rentalSetup','One-time setup ($)')}</div><p class="field-note">All reserved hours are billed, including idle time. Electricity is included in the rental price.</p>`)+disclosure('Pay per use: provider prices',`<p class="field-note">Pay per use means accessing the same AI model through a provider’s API. Providers bill for tokens: small pieces of text read and written. Enter prices per million tokens for this model.</p><div class="fields">${field('apiInput','Text read ($/1M tokens)',0.01)}${field('apiOutput','Text written ($/1M tokens)',0.01)}${field('apiCached','Reused text ($/1M tokens)',0.01)}${field('cache','Text reuse (%)',1,100)}</div>`);
const systems=select('model','AI model used in all comparisons',models.map(m=>[m.id,m.name]))+select('hardware','System you would buy',hardware.map(h=>[h.id,`${h.name} · ${h.variant}`]))+select('rentalHardware','System you would rent',hardware.map(h=>[h.id,`${h.name} · ${h.variant}`]))+`<p class="field-note">These are example systems, not purchasing recommendations. Changing the purchase system loads its budget. Changing the rental system keeps your entered hourly rate—check the provider’s quote.</p>`;
const usage=`<p class="field-note" id="template-description"></p><div class="fields">${field('agents','AI assistants per person')}${field('activity','Active at the same time (%)',1,100)}${field('requests','Model calls / assistant / day')}${field('days','Working days / month',0.01,30)}${field('hours','Working hours / day',0.5,24)}${field('input','Input tokens / call')}${field('output','Output tokens / call')}${field('batch','Parallel calls (0 = automatic)',1,4096)}</div><p class="field-note">One task can involve several model calls. Presets are illustrative assumptions, not measured business averages. Editing these fields switches to custom usage.</p>`;
const expert=`<p class="field-note">For your technical team: calibrate against the exact model and system. Zero rate overrides use an estimate; rates are batch-1 before speed/batch adjustments.</p><div class="fields">${select('bits','Weight precision',[[4,'4-bit / Q4'],[8,'8-bit / Q8'],[16,'16-bit / BF16']])}${field('context','Context / sequence')}${field('efficiency','Local utilization cap (%)',1,100)}${field('decodeOverride','Local decode tokens/sec',0.1)}${field('prefillOverride','Local prefill tokens/sec',0.1)}${field('speed','Local speed multiplier (%)')}${field('batchExponent','Local batch exponent',0.05,1)}${field('kv','Cache MB / token',0.01)}${field('headroom','Runtime overhead (%)')}${field('memory','Local memory GB')}${field('reserve','Reserved memory GB')}${field('idle','Idle system watts')}${field('load','Loaded system watts')}${field('cooling','Cooling multiplier',0.05)}${field('rentalMemory','Rental memory GB')}${field('rentalReserve','Rental reserved GB')}${field('rentalEfficiency','Rental utilization cap (%)',1,100)}${field('rentalSpeed','Rental speed multiplier (%)')}${field('rentalDecodeOverride','Rental decode tokens/sec',0.1)}${field('rentalPrefillOverride','Rental prefill tokens/sec',0.1)}${field('rentalBatchExponent','Rental batch exponent',0.05,1)}</div>`;
const opened=[...$('controls').querySelectorAll('details[open]')].map(d=>d.querySelector('summary').textContent);
$('controls').innerHTML=group('01','Tell us about your team',workload)+disclosure('02 · Review prices & budget',prices)+disclosure('03 · Choose the systems to compare',systems)+disclosure('Adjust usage assumptions',usage)+disclosure('Technical settings',expert);
for(const d of $('controls').querySelectorAll('details'))d.open=opened.includes(d.querySelector('summary').textContent);
}
function setHardware(id){const h=hardware.find(h=>h.id===id);state.hardware=id;for(const k of ['price','memory','reserve','idle','load'])state[k]=h[k];state.decodeOverride=0;state.prefillOverride=0;}
function setRental(id){const h=hardware.find(h=>h.id===id);state.rentalHardware=id;state.rentalMemory=h.memory;state.rentalReserve=h.reserve;state.rentalDecodeOverride=0;state.rentalPrefillOverride=0;}
function drawChart(r){const w=780,h=250,left=67,right=14,top=20,bottom=35;const n=r.s.months;const resale=r.s.price*r.s.resale/100;const max=Math.max(r.capital+r.recurring*n,r.cloud*n,r.rentalTco,1)*1.12;const x=t=>left+t/n*(w-left-right);const y=v=>h-bottom-v/max*(h-top-bottom);
const lines=[{color:'#477a50',f:t=>r.capital+r.recurring*t-(t===n?resale:0)},{color:'#8b73b0',f:t=>r.cloud*t},{color:'#aab1a3',f:t=>r.s.rentalSetup+r.rentalMonthly*t}];
let svg=`<svg viewBox="0 0 ${w} ${h}" role="img" aria-labelledby="chart-title chart-desc"><title id="chart-title">Cumulative inference costs over ${n} months</title><desc id="chart-desc">At month ${n}, local plus overflow costs ${money(r.localTco)}, API costs ${money(r.cloudTco)}, and rented hardware plus overflow costs ${money(r.rentalTco)}.</desc>`;
for(let i=0;i<=4;i++){const v=max*i/4;svg+=`<line x1="${left}" y1="${y(v)}" x2="${w-right}" y2="${y(v)}" stroke="#e8ecdf" stroke-dasharray="3 4"/><text x="${left-12}" y="${y(v)+4}" text-anchor="end" fill="#8b957f" font-size="10">${money(v)}</text>`;}
for(const t of [...new Set([0,Math.round(n/4),Math.round(n/2),Math.round(n*3/4),n])])svg+=`<text x="${x(t)}" y="${h-10}" text-anchor="middle" fill="#8b957f" font-size="10">${t===0?'Today':`Month ${t}`}</text>`;
for(const line of lines){const points=Array.from({length:n+1},(_,t)=>`${x(t)},${y(line.f(t))}`).join(' ');svg+=`<polyline points="${points}" fill="none" stroke="${line.color}" stroke-width="2.5" ${line.color==='#aab1a3'?'stroke-dasharray="5 5"':''}/><circle cx="${x(n)}" cy="${y(line.f(n))}" r="4" fill="${line.color}"/>`;}
const laterPayback=combinedPayback(r.payback,r.paybackVsRental);
if(laterPayback!==null&&laterPayback<=n){svg+=`<line data-payback-month="${laterPayback}" x1="${x(laterPayback)}" y1="${top}" x2="${x(laterPayback)}" y2="${h-bottom}" stroke="#5c8050" stroke-dasharray="3 4"/><text x="${Math.min(x(laterPayback)+7,w-200)}" y="15" fill="#547144" font-size="10">Buying pays back · ${num(laterPayback,1)} months</text>`;}
$('payback-note').textContent=laterPayback===null?'Buying does not pay back against both alternatives with these assumptions.':laterPayback>n?`Buying pays back against both alternatives at ${num(laterPayback,1)} months, beyond this ${n}-month view.`:`Buying recovers its upfront cost against both alternatives after ${num(laterPayback,1)} months. The later crossing is with ${r.payback>=r.paybackVsRental?'pay per use':'renting'}. This excludes resale value.`;
$('chart').innerHTML=svg+'</svg>'; $('horizon').textContent=`${n} months`;
}
function render(){const r=calculate(state); $('workload-estimate').textContent=`Plan: ${num(state.users)} people · ${num(state.days,2)} working days/month · ${num(state.hours)} hours/day.`; $('template-description').textContent=workloads.find(w=>w.id===state.workload)?.note||'Custom usage. Choose a template to restore a standard set of estimates.';
const eligible=[{id:'buy',name:r.localFraction<0.999?'Buying + pay per use':'Buying your own system',cost:r.localTco,valid:r.fits&&r.contextOk},{id:'rent',name:r.rentalFraction<0.999?'Renting + pay per use':'Renting a system',cost:r.rentalTco,valid:r.rentalFits&&r.contextOk},{id:'api',name:'Paying per use',cost:r.cloudTco,valid:r.contextOk}].filter(o=>o.valid).sort((a,b)=>a.cost-b.cost);
const best=eligible[0],runner=eligible[1];
const meaningful=r.requests>0&&r.contextOk;
const difference=runner&&best?runner.cost-best.cost:0;
const tied=runner&&Math.abs(difference)<1;
const winner=meaningful&&!tied?best?.id:null;
const title=!r.contextOk?'Ask your technical team to review this setup':!r.requests?'Add your team’s expected usage':tied?'These options cost about the same':`${best.name} has the lowest estimated cost`;
const explanation=!r.contextOk?'The selected usage exceeds the model’s allowed text length. Cost comparisons are not ready for a decision.':!r.requests?'Enter at least one user and a usage template to compare meaningful costs.':tied?'The difference is less than $1 over this period. Compare support needs and availability before deciding.':`${money(best.cost)} over ${state.months} months${runner?`, about ${money(difference)} less than the next option`:''}. This compares the systems and prices below; it does not search every available supplier.`;
const card=(id,title,total,monthly,upfront,description)=>`<div class="metric ${winner===id?'primary':''}"><div class="label">${title}</div><strong>${money(total)}</strong><small>Total over ${state.months} months</small><div class="cost-detail">${money(upfront)} upfront<br>${money(monthly)} ongoing / month</div><p>${description}</p>${winner===id?'<span class="best-label">Lowest estimated cost</span>':''}</div>`;
const capacityMessage=!r.fits?'The purchase system cannot hold this model; its estimate includes buying the system and sending all work to a pay-per-use provider. It is excluded from the recommendation.':r.localFraction<0.999&&r.requests>0?`The purchase system handles about ${num(r.localFraction*100)}% of your work. The remaining work uses a pay-per-use provider, included in the price.`:'The purchase system is estimated to handle your workload.';
const rentalMessage=!r.rentalFits?'The rental system cannot hold this model and is excluded from the recommendation. Its reserved hours and pay-per-use charges are still shown.':r.rentalFraction<0.999&&r.requests>0?`The rented system handles about ${num(r.rentalFraction*100)}% of your work; the rest is included as pay-per-use charges.`:'The rented system is estimated to handle your workload.';
$('summary').innerHTML=`<section class="recommendation"><div class="eyebrow">YOUR COST COMPARISON</div><h2>${title}</h2><p>${explanation}</p><p class="assumption-note">Planning estimate, not a vendor quote. Prices and performance are assumptions. Have your technical team confirm the systems, provider availability and service quality before committing.</p></section><div class="metrics">${card('buy','Buy a system',r.localTco,r.recurring,r.capital,'Own the equipment. Your team manages it and pays its running costs.')}${card('rent','Rent a system',r.rentalTco,r.rentalMonthly,state.rentalSetup,'Reserve equipment from a provider. Pay for the hours reserved, even when idle.')}${card('api','Pay per use',r.cloudTco,r.cloud,0,'Use a provider’s AI service. Pay for the amount of text processed (API usage).')}</div><div class="plain-assumptions"><p><strong>What is being compared?</strong> ${r.m.name} for all three options, serving the same team and workload. Buying: ${r.h.name} (${r.h.variant}). Renting: ${r.rentalHardware.name} (${r.rentalHardware.variant}).</p><p>${capacityMessage} ${rentalMessage}</p><p>Both hardware options include extra pay-per-use charges when they cannot handle all demand. ${r.h.proxy||r.rentalHardware.proxy?'Mac M5 performance uses an M4 placeholder benchmark.':''} Pay-per-use provider capacity is not verified. Totals include any resale value at the end; ongoing monthly costs exclude the upfront payment.</p></div>`;
const payback=r.payback===null?'No payback':`${num(r.payback,1)} months`;
const row=(label,...cells)=>`<tr><th scope="row">${label}</th>${cells.map(c=>`<td>${c}</td>`).join('')}</tr>`;
$('comparison').innerHTML=`<div class="eyebrow">SAME MODEL · SAME WORKLOAD</div><h2>Buy, rent, or use the API</h2><p class="caption">${r.m.name} · ${num(r.requests)} requests/month · ${num(state.input)} input + ${num(state.output)} output tokens/request. Hardware estimates use ${state.bits}-bit weights and batch ${r.batch}. API pricing must match this model; provider precision and performance may differ.</p><div class="table-wrap"><table><thead><tr><th>Comparison</th><th>Buy hardware</th><th>Rent hardware</th><th>Model API</th></tr></thead><tbody>${row('Configuration',`${r.h.name}<small>${r.h.variant}</small>`,`${r.rentalHardware.name}<small>${r.rentalHardware.variant}</small>`,r.m.name)}${row('Upfront',money(r.capital),money(state.rentalSetup),money(0))}${row('Monthly infrastructure',`${money(r.powerCost+state.maintenance)}<small>Electricity + admin</small>`,`${money(r.rentalCompute+state.rentalExtra)}<small>${num(state.rentalHours)} h × $${num(state.rental,2)} + extras</small>`,'Included in token price')}${row('Monthly API charges',`${money(r.overflow)}<small>Overflow</small>`,`${money(r.rentalOverflow)}<small>Overflow</small>`,money(r.cloud))}${row('Total monthly',money(r.recurring),money(r.rentalMonthly),money(r.cloud))}${row(`${state.months}-month total`,money(r.localTco),money(r.rentalTco),money(r.cloudTco))}${row('Memory fit',r.fits?'Fits estimate':'Does not fit',r.rentalFits?'Fits estimate':'Does not fit','Provider-managed')}${row('Requests/month capacity',num(r.capacity),num(r.rentalCapacity),'Not modeled')}${row('Served on hardware',`${num(r.localFraction*100,1)}%`,`${num(r.rentalFraction*100,1)}%`,'All via API')}${row('Decode tok/s per stream',num(r.perStream,1),num(r.rentalDecode/r.batch,1),'Provider-dependent')}</tbody></table></div><p class="caption">Buy vs API cash payback: <strong>${payback}</strong>. Buy vs rent cash payback: <strong>${r.paybackVsRental===null?'No sustained payback':`${num(r.paybackVsRental,1)} months`}</strong>. Payback excludes resale; values beyond ${state.months} months are outside this horizon. Buy-vs-rent payback requires lower purchase-path monthly costs and recovers the upfront difference. Horizon totals include resale. Rental capacity uses ${num(r.rentalServingHours)} of ${num(state.rentalHours)} billed hours within the workload window.</p>`;
drawChart(r);
$('capacity').innerHTML=`<div class="section-heading"><div><span class="eyebrow">WILL IT ACTUALLY RUN?</span><h2>Memory & serving capacity</h2></div><span class="pill">${r.fits&&r.contextOk?'Estimated fit':'Configuration blocked'}</span></div><div class="memory-track"><div style="width:${Math.min(100,r.weight/Math.max(1,r.available)*100)}%"></div><div class="cache" style="width:${Math.min(100,r.cache/Math.max(1,r.available)*100)}%"></div></div><div class="memory-caption"><span>${num(r.required,1)} GB required</span><span>${num(r.available)} GB usable</span></div><div class="capacity-grid"><div><strong>${r.batch}</strong><small>concurrent sequences</small></div><div><strong>${num(r.perStream,1)}</strong><small>decode tok/s per stream*</small></div><div><strong>${num(r.ttft,1)} s</strong><small>prefill time per batch*</small></div><div><strong>${num(r.localFraction*100,1)}%</strong><small>demand served locally</small></div></div><p class="caption">${num(r.weight,1)} GB weights + overhead · ${num(r.cache,1)} GB cache · ${num(r.decode)} aggregate decode tok/s* · ${num(r.capacity)} estimated requests/month capacity · ${num(r.latency,1)} s batch latency* · ${num(r.energyKwh)} kWh/month (${money(r.powerCost)}). *Potential speed if runnable; no queue/network/tool time.</p><p class="caption">${r.thresholdFeasible?`At this ${state.months}-month horizon, ownership reaches economic break-even at approximately ${num(Math.ceil(r.threshold))} requests/month with this token mix.`:'No achievable volume break-even within the selected horizon and estimated local capacity.'}</p>`;
$('hardware-table').innerHTML=hardware.map(h=>{const selected=h.id===state.hardware;const alt=selected?r:calculate({...state,hardware:h.id,price:h.price,memory:h.memory,reserve:h.reserve,idle:h.idle,load:h.load,decodeOverride:0,prefillOverride:0});return `<tr class="${selected?'selected':''}"><td><button type="button" data-hardware="${h.id}">${h.name}${h.proxy?'<span class="tag">M4 PROXY</span>':''}<small>${h.variant}${selected?' · SELECTED':''}</small></button></td><td>${money(alt.localTco)}</td><td>${money(alt.rentalTco)}</td><td>${money(alt.cloudTco)}</td><td>${num(alt.localFraction*100)}%${alt.fits?'':'<small>Does not fit</small>'}</td><td>${alt.paybackVsRental===null?'—':`${num(alt.paybackVsRental,1)} mo`}</td></tr>`;}).join('');
try{localStorage.setItem('inference-ledger-v1',JSON.stringify(state));}catch{}
}
$('methodology').innerHTML=`<ul><li>Requests/month = users × agents/user × requests/agent/day × work days. Active percentage controls peak concurrency, not request volume. Auto batch rounds up active concurrency; manual batch is independent.</li><li>Weights GB = total parameters (billions) × precision bits ÷ 8 × overhead. All MoE experts consume memory. Cache GB = context × cache MB/token × batch ÷ 1,000. Usable memory = installed − reserve. No CPU offload is modeled.</li><li>Batch-1 performance = reference rate × √(3.3/active parameters) × (30.5/total parameters)^0.15 × (4/precision bits). This unvalidated heuristic is for sensitivity analysis. Overrides replace that rate; both then multiply by the speed factor and batch^exponent. Aggregate decode ÷ batch estimates per-stream speed.</li><li>Service seconds/request = input tokens ÷ aggregate prefill + output tokens ÷ aggregate decode. Monthly capacity = serving seconds × utilization cap ÷ service seconds. Local requests = minimum of demand and capacity; remaining requests incur API costs. Invalid memory or context yields zero local capacity. Prefix-cache discounts affect API billing only.</li><li>Power = [idle W × 720 + (loaded − idle W) × active hours] ÷ 1,000 × cooling multiplier. Active hours derive from local requests and service seconds. Monthly ownership = electricity + maintenance + API overflow.</li><li>Cash payback = (purchase + setup) ÷ (API-only monthly cost − ownership monthly cost), when savings are positive. TCO includes resale only at the final month. Volume threshold amortizes purchase and setup minus resale over the horizon, including fixed and per-request energy; it is reported only if local capacity can reach it.</li><li>No financing, taxes, hardware replacement, growth, quality parity or guaranteed uptime is assumed. Enter all-in purchase/setup quotes and administration costs. API-only availability and rate limits are not modeled. Rental uses its own memory, throughput, utilization and provisioned hours for the same model, context, batch and demand. Rental capacity uses the smaller of billed hours and workload serving hours. Monthly rental = all provisioned hours × whole-system hourly price + extras + same-model API overflow. Rental setup is paid upfront. Buy-vs-rent cash payback recovers the upfront difference only when ownership has lower recurring expense. Provider availability, API capacity and model precision parity must be verified separately.</li></ul>`;
$('sources').innerHTML=`<p>Catalog reviewed September 22, 2026. A curated shortlist for software engineering and security-code analysis, not a universal ranking or a claim of cyber benchmark leadership. Validate task success and licensing before choosing a model. API rates are user-defined and persist when switching models.</p><p><a href="${benchmarkSource}" target="_blank" rel="noreferrer">MLX-LM M4 Max benchmark reference</a>: Qwen3-30B-A3B-Instruct-2507 Q4, 113.33 generation tok/s, 1,753.90 prompt tok/s, 2,048 prompt / 128 generation tokens, MLX-LM 0.28.2, 64 GB M4 Max. Both M5 configurations use this same proxy before heuristic scaling. It is not a measurement of M5, the Coder checkpoint, long contexts or batching.</p>${models.map(m=>`<div class="source-item"><strong><a href="${m.source}" target="_blank" rel="noreferrer">${m.name}</a> · ${m.tag}</strong><p>${m.params}B total / ${m.active}B active parameters · context ${num(m.context)}. ${m.note}</p></div>`).join('')}${hardware.map(h=>`<div class="source-item"><strong><a href="${h.source}" target="_blank" rel="noreferrer">${h.name} · ${h.variant}</a></strong><p>${h.note} Power, price and throughput are planning inputs.</p></div>`).join('')}`;
$('controls').addEventListener('input',e=>{const el=e.target;if(!el.name||el.tagName==='SELECT')return;if(el.value===''||!el.validity.valid)return;state[el.name]=Number(el.value);if(['agents','activity','batch','requests','days','hours','input','output','context'].includes(el.name)){state.workload='custom';$('controls').querySelector('[name=workload]').value='custom';}state=normalize(state);render();});
$('controls').addEventListener('change',e=>{const el=e.target;if(el.tagName!=='SELECT')return;if(el.name==='workload'){state=applyWorkload(state,el.value);}else if(el.name==='hardware')setHardware(el.value);else if(el.name==='rentalHardware')setRental(el.value);else if(el.name==='model'){state.model=el.value;state.kv=models.find(m=>m.id===el.value).kv;state.rentalDecodeOverride=0;state.rentalPrefillOverride=0;state.decodeOverride=0;state.prefillOverride=0;}else state[el.name]=Number(el.value);controls();render();});
$('hardware-table').addEventListener('click',e=>{const btn=e.target.closest('[data-hardware]');if(btn){setHardware(btn.dataset.hardware);controls();render();}});
$('reset').addEventListener('click',()=>{state=applyWorkload({...defaults},'chat');controls();render();});
$('export').addEventListener('click',()=>{const r=calculate(state);const blob=new Blob([JSON.stringify({schemaVersion:3,catalogReviewed:'2026-09-22',exportedAt:new Date().toISOString(),assumptions:'Planning estimates, not measured benchmarks or quotes',inputs:state,results:r},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='inference-ledger-scenario.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
controls();render();
