export const reviewed="2026-09-22";
export const models=[
  {
    "id": "nemotron-lightning",
    "name": "NVIDIA: Nemotron 3.5 Lightning",
    "source": "https://huggingface.co/nvidia/NVIDIA-Nemotron-3.5-Lightning-30B-A3B-BF16",
    "apiSource": "https://openrouter.ai/api/v1/models/nvidia/nemotron-3.5-lightning/endpoints",
    "apiModel": "nvidia/nemotron-3.5-lightning",
    "provider": "Darkbloom via OpenRouter",
    "providerTag": "darkbloom/int4",
    "quantization": "int4",
    "context": 262144,
    "maxOutput": 32768,
    "maxInput": null,
    "input": 0.065,
    "output": 0.18,
    "cached": null
  },
  {
    "id": "kimi3",
    "name": "MoonshotAI: Kimi K3",
    "source": "https://huggingface.co/moonshotai/Kimi-K3",
    "apiSource": "https://openrouter.ai/api/v1/models/moonshotai/kimi-k3/endpoints",
    "apiModel": "moonshotai/kimi-k3",
    "provider": "Relace via OpenRouter",
    "providerTag": "relace/fp4",
    "quantization": "fp4",
    "context": 1048576,
    "maxOutput": 943718,
    "maxInput": null,
    "input": 1.7,
    "output": 8.5,
    "cached": 0.16999999999999998
  },
  {
    "id": "nemotron-ultra",
    "name": "NVIDIA: Nemotron 3 Ultra",
    "source": "https://huggingface.co/nvidia/NVIDIA-Nemotron-3-Ultra-550B-A55B-BF16",
    "apiSource": "https://openrouter.ai/api/v1/models/nvidia/nemotron-3-ultra-550b-a55b/endpoints",
    "apiModel": "nvidia/nemotron-3-ultra-550b-a55b",
    "provider": "DeepInfra via OpenRouter",
    "providerTag": "deepinfra/fp4",
    "quantization": "fp4",
    "context": 262144,
    "maxOutput": 16384,
    "maxInput": null,
    "input": 0.5,
    "output": 2.2,
    "cached": 0.09999999999999999
  },
  {
    "id": "nemotron-super",
    "name": "NVIDIA: Nemotron 3 Super",
    "source": "https://huggingface.co/nvidia/NVIDIA-Nemotron-3-Super-120B-A12B-FP8",
    "apiSource": "https://openrouter.ai/api/v1/models/nvidia/nemotron-3-super-120b-a12b/endpoints",
    "apiModel": "nvidia/nemotron-3-super-120b-a12b",
    "provider": "DeepInfra via OpenRouter",
    "providerTag": "deepinfra/bf16",
    "quantization": "bf16",
    "context": 262144,
    "maxOutput": 16384,
    "maxInput": null,
    "input": 0.08499999999999999,
    "output": 0.39999999999999997,
    "cached": null
  },
  {
    "id": "minimax",
    "name": "MiniMax: MiniMax M2.5",
    "source": "https://huggingface.co/MiniMaxAI/MiniMax-M2.5",
    "apiSource": "https://openrouter.ai/api/v1/models/minimax/minimax-m2.5/endpoints",
    "apiModel": "minimax/minimax-m2.5",
    "provider": "Venice via OpenRouter",
    "providerTag": "venice",
    "quantization": "unknown",
    "context": 198000,
    "maxOutput": 32768,
    "maxInput": null,
    "input": 0.27,
    "output": 0.95,
    "cached": 0.03
  },
  {
    "id": "qwen80",
    "name": "Qwen: Qwen3 Coder Next",
    "source": "https://huggingface.co/Qwen/Qwen3-Coder-Next",
    "apiSource": "https://openrouter.ai/api/v1/models/qwen/qwen3-coder-next/endpoints",
    "apiModel": "qwen/qwen3-coder-next",
    "provider": "Parasail via OpenRouter",
    "providerTag": "parasail/bf16",
    "quantization": "bf16",
    "context": 262144,
    "maxOutput": 235929,
    "maxInput": null,
    "input": 0.12,
    "output": 0.7999999999999999,
    "cached": 0.07
  },
  {
    "id": "kimi25",
    "name": "MoonshotAI: Kimi K2.5",
    "source": "https://huggingface.co/moonshotai/Kimi-K2.5",
    "apiSource": "https://openrouter.ai/api/v1/models/moonshotai/kimi-k2.5/endpoints",
    "apiModel": "moonshotai/kimi-k2.5",
    "provider": "SiliconFlow via OpenRouter",
    "providerTag": "siliconflow/int4",
    "quantization": "int4",
    "context": 262144,
    "maxOutput": 235929,
    "maxInput": null,
    "input": 0.44999999999999996,
    "output": 2.25,
    "cached": 0.07
  },
  {
    "id": "nemotron-nano",
    "name": "NVIDIA: Nemotron 3 Nano 30B A3B",
    "source": "https://huggingface.co/nvidia/NVIDIA-Nemotron-3-Nano-30B-A3B-BF16",
    "apiSource": "https://openrouter.ai/api/v1/models/nvidia/nemotron-3-nano-30b-a3b/endpoints",
    "apiModel": "nvidia/nemotron-3-nano-30b-a3b",
    "provider": "Novita via OpenRouter",
    "providerTag": "novita/fp4",
    "quantization": "fp4",
    "context": 262144,
    "maxOutput": 32768,
    "maxInput": null,
    "input": 0.049999999999999996,
    "output": 0.19999999999999998,
    "cached": null
  },
  {
    "id": "deepseek",
    "name": "DeepSeek: DeepSeek V3.2",
    "source": "https://huggingface.co/deepseek-ai/DeepSeek-V3.2",
    "apiSource": "https://openrouter.ai/api/v1/models/deepseek/deepseek-v3.2/endpoints",
    "apiModel": "deepseek/deepseek-v3.2",
    "provider": "DeepInfra via OpenRouter",
    "providerTag": "deepinfra/fp4",
    "quantization": "fp4",
    "context": 163840,
    "maxOutput": 16384,
    "maxInput": null,
    "input": 0.26,
    "output": 0.38,
    "cached": 0.13
  },
  {
    "id": "oss120",
    "name": "OpenAI: gpt-oss-120b",
    "source": "https://huggingface.co/openai/gpt-oss-120b",
    "apiSource": "https://openrouter.ai/api/v1/models/openai/gpt-oss-120b/endpoints",
    "apiModel": "openai/gpt-oss-120b",
    "provider": "AkashML via OpenRouter",
    "providerTag": "akashml/bf16",
    "quantization": "bf16",
    "context": 131072,
    "maxOutput": 117964,
    "maxInput": null,
    "input": 0.03,
    "output": 0.16999999999999998,
    "cached": 0.03
  },
  {
    "id": "qwen30",
    "name": "Qwen: Qwen3 Coder 30B A3B Instruct",
    "source": "https://huggingface.co/Qwen/Qwen3-Coder-30B-A3B-Instruct",
    "apiSource": "https://openrouter.ai/api/v1/models/qwen/qwen3-coder-30b-a3b-instruct/endpoints",
    "apiModel": "qwen/qwen3-coder-30b-a3b-instruct",
    "provider": "Novita via OpenRouter",
    "providerTag": "novita/fp8",
    "quantization": "fp8",
    "context": 160000,
    "maxOutput": 32768,
    "maxInput": null,
    "input": 0.07,
    "output": 0.27,
    "cached": null
  }
];
const apple='https://www.apple.com/mac-studio/specs/';
const spark='https://www.nvidia.com/en-us/products/workstations/dgx-spark/';
const framework='https://frame.work/desktop?tab=machine-learning';
export const hardware=[
 {id:'spark',name:'NVIDIA DGX Spark',memory:128,kind:'unified',price:4699,source:spark,priceSource:'https://forums.developer.nvidia.com/t/2-23-2026-price-change-announcement/361713',priceKind:'US MSRP, announced February 23, 2026; not a checkout quote',package:'GB10, 20-core Arm CPU, 128 GB unified memory, 4 TB NVMe, DGX OS, ConnectX-7, supplied enclosure and 240 W power supply. PSU rating is not measured consumption.'},
 {id:'strix-amd-128',name:'AMD Ryzen AI Halo · Strix Halo',memory:128,kind:'unified',price:3999,source:'https://www.amd.com/en/products/processors/desktops/ryzen/ryzen-ai-halo.html',priceSource:'https://www.amd.com/en/blogs/2026/amd-ryzen-ai-halo-is-designed-for-the-agentic-era.html',priceKind:'AMD-reported Micro Center system price, July 2026 comparison; confirm checkout',package:'Complete Ryzen AI Halo developer platform: Ryzen AI Max+ 395, 128 GB unified memory. Storage and OS variant must be confirmed with the retailer.'},
 {id:'strix-framework-64',name:'Framework Desktop Max+ 395 · 64 GB',memory:64,kind:'unified',gpuCeiling:48,price:null,source:framework,package:'Framework desktop chassis and Ryzen AI Max+ 395 / Radeon 8060S platform, 64 GB onboard RAM. Select SSD and OS in a complete-system quote; no bare-mainboard price is used.'},
 {id:'strix-framework-128',name:'Framework Desktop Max+ 395 · 128 GB',memory:128,kind:'unified',gpuCeiling:96,price:null,source:framework,package:'Framework desktop chassis and Ryzen AI Max+ 395 / Radeon 8060S platform, 128 GB onboard RAM. SSD and OS need a complete-system quote. Vendor lists 96 GB dedicated GPU allocation; Linux can differ.'},
 {id:'strix-hp-128',name:'HP Z2 Mini G1a · BN8E8UA',memory:128,kind:'unified',price:null,source:'https://www.hp.com/us-en/shop/pdp/hp-z2-mini-g1a-workstation-desktop-pc-wolf-pro-security-edition-bn8e8ua-aba',package:'Ryzen AI Max+ PRO 395, Radeon 8060S, 128 GB RAM, 1 TB NVMe, Windows 11 Pro, OEM mini chassis and 300 W power adapter. Price not verified.'},
 ...[256,512].map(memory=>({id:`m5-${memory}`,name:`Mac Studio M5 Ultra · ${memory} GB`,memory,kind:'unified',price:null,source:apple,package:`36-core CPU / 80-core GPU, ${memory} GB unified RAM, 1 TB SSD, macOS, complete Mac Studio. Exact configured price and inference performance need evidence; no M4 proxy is used.`})),
 {id:'hp-2000',name:'HP Z2 Mini G1i · RTX 2000 Ada',memory:16,kind:'VRAM',price:null,source:'https://www.hp.com/us-en/shop/pdp/hp-z2-mini-g1i-workstation-desktop-pc-wolf-pro-security-edition-p-bp6k5ua-aba-1',package:'BP6K5UA: Core Ultra 7 265, RTX 2000 Ada 16 GB, 32 GB host RAM, 1 TB SSD, Windows 11 Pro, complete OEM workstation. Host RAM is not VRAM.'},
 {id:'hp-4000',name:'HP Z2 Mini G1i · RTX 4000 Ada',memory:20,kind:'VRAM',price:null,source:'https://www.hp.com/us-en/shop/pdp/hp-z2-mini-g1i-workstation-desktop-pc-wolf-pro-security-edition-p-bp6k7ua-aba-1',package:'BP6K7UA: Core Ultra 7 265, RTX 4000 Ada 20 GB, 64 GB host RAM, 1 TB SSD, Windows 11 Pro, complete OEM workstation.'},
 ...[['5080',16],['5090',32],['PRO 4000 Blackwell',24],['PRO 5000 Blackwell',48],['PRO 6000 Blackwell WS',96]].map(([gpu,memory])=>({id:`puget-${gpu.replaceAll(' ','-').toLowerCase()}`,name:`Puget workstation · RTX ${gpu}`,memory,kind:'VRAM',price:null,source:'https://www.pugetsystems.com/products/workstations/configure/',package:`Vendor-configured complete workstation with RTX ${gpu}. CPU, host RAM, SSD, chassis, PSU, cooling and OS must be specified in the vendor quote. Published GPU add-on prices are not complete-system prices.`,needsBuild:true})),
 {id:'supermicro-h100',name:'Supermicro 4U · 8× H100 HGX',memory:640,kind:'VRAM',price:null,source:'https://www.supermicro.com/en/products/system/gpu/4u/sys-421ge-tnhr2-lcc',package:'SYS-421GE-TNHR2-LCC H100 configuration: HGX 8-GPU platform, dual Xeon, liquid cooling. CPU SKU, RAM, storage and onsite cooling installation require an integrated system quote.',needsBuild:true},
 ...[2,4].map(nodes=>({id:`spark-x${nodes}`,name:`${nodes}× DGX Spark cluster`,memory:128*nodes,kind:'distributed unified',price:null,source:spark,package:`${nodes} complete GB10 / 128 GB / 4 TB Spark systems plus ConnectX networking. Total memory is arithmetic across nodes, not automatically pooled. Cluster quote must include networking. No scaling factor is assumed.`,needsBuild:true})),
 ...[2,4].map(nodes=>({id:`m5-512-x${nodes}`,name:`${nodes}× Mac Studio 512 GB · EXO cluster`,memory:512*nodes,kind:'distributed unified',price:null,source:apple,runtimeSource:'https://github.com/exo-explore/exo',package:`${nodes} complete M5 Ultra 36-core CPU / 80-core GPU, 512 GB RAM, 1 TB SSD systems with Thunderbolt networking. EXO documents RDMA support; exact topology, model compatibility and performance require validation. Networking must be included in the cluster quote.`,needsBuild:true}))
];
// All rates below are full-instance USD/hour, computed from the quoted per-GPU rate.
// Specs and on-demand rates: https://lambda.ai/instances, checked 2026-09-22.
export const rentals=[
 ['quadro',1,'Quadro RTX 6000',24,14,46,'512 GiB',.69],
 ['a6000',1,'A6000',48,14,100,'512 GiB',1.09],
 ['a100',1,'A100 PCIe',40,30,225,'512 GiB',1.99],
 ['h100-pcie',1,'H100 PCIe',80,26,225,'1 TiB',3.29],
 ['h100',1,'H100 SXM',80,26,225,'2.75 TiB',4.29],
 ['gh200',1,'GH200',96,64,432,'4 TiB',2.29],
 ['a6000-x2',2,'A6000',48,28,200,'1 TiB',1.09],
 ['a6000-x4',4,'A6000',48,56,400,'1 TiB',1.09],
 ['h100-x2',2,'H100 SXM',80,52,450,'5.5 TiB',4.19],
 ['h100-x4',4,'H100 SXM',80,104,900,'11 TiB',4.09],
 ['h100-x8',8,'H100 SXM',80,208,1800,'22 TiB',3.99],
 ['b200',1,'B200 SXM6',180,26,360,'2.75 TiB',6.99],
 ['b200-x8',8,'B200 SXM6',180,208,2900,'22 TiB',6.69]
].map(([id,gpus,gpu,vram,cpu,ram,storage,perGpu])=>({id,name:`Lambda ${gpus}× ${gpu}`,gpu,gpus,memory:gpus*vram,vram,cpu,ram,storage,perGpu,hourly:Number((gpus*perGpu).toFixed(2)),source:'https://lambda.ai/instances',billingSource:'https://docs.lambda.ai/public-cloud/on-demand/billing/',package:`${cpu} vCPU · ${ram} GiB host RAM · ${storage} local SSD`,terms:'On-demand USD; tax extra. Region/stock not guaranteed. Persistent storage and other extras require a quote. Not a performance-equivalent substitute.'}));
export const workloads=[['chat','Simple Chat'],['research','Research'],['bizdev','Business Development'],['swe','AI-assisted SWE'],['swe-factory','Full-auto software factory · 24/7'],['support','Customer Support'],['writing','Writing & Content'],['security','Security Analysis']];
export const defaults={autoHardware:1,overrides:'',workload:'swe',users:1,model:'qwen80',hardware:'spark',rental:'a6000-x4',autoRental:1,autoModel:1,start:'2026-09',calls:null,input:null,output:null,concurrency:null,usageSource:'',localRph:null,rentalRph:null,localMemory:null,rentalMemory:null,localAvailable:null,rentalAvailable:null,localEvidence:'',rentalEvidence:'',localRuntime:'',rentalRuntime:'',quote:null,quoteSource:'',buildDetails:'',localSetup:null,rentalSetup:null,localExtras:null,rentalExtras:null,apiExtras:null,costSource:'',itKwh:null,coolingKwh:null,energySource:'',tariff:'gs1',baselineKwh:null,peakKw:null,tariffConfirmed:0,localTax:1,billRate:null,billSource:'',purchaseDiscount:0,rentalDecline:0,apiDecline:0,priceEvidence:'',modelRefresh:null,hardwareRefresh:null,lifecycleSource:''};
