const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=(v,d=1)=>Number.isFinite(v)?v.toLocaleString('en-US',{maximumFractionDigits:d}):'Check advanced inputs';
const money=v=>Number.isFinite(v)?new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(v):'Check advanced inputs';
export function comparisonData(r){
 const {s,first:f,last:l}=r;
 const coverage=capacity=>Number.isFinite(capacity)&&Number.isFinite(f.requests)?(f.requests>0?Math.min(1,capacity/f.requests):1):null;
 return [
 {key:'buy',title:'Buy hardware',name:r.h.name,upfront:r.capital,monthly:f.buyMonthly,total:l.buy,coverage:coverage(f.localCapacity),capacity:f.localCapacity,rph:s.localRph,
 costs:[['IT electricity',r.power?.it],['Cooling electricity',r.power?.cooling],['Support & other costs',s.localExtras],['Extra API usage',f.localOverflow],['API fees for overflow',f.localOverflow>0?s.apiExtras:0]],
 initial:[['Equipment after discount',r.purchase===null?null:r.purchase*(1-s.purchaseDiscount/100)],['Setup, tax & other extras',s.localSetup]],
 note:'You own and maintain the system. Excess work uses the API; those charges are included.'},
 {key:'rent',title:'Rent hardware',name:r.r.name,upfront:s.rentalSetup,monthly:f.rentMonthly,total:l.rent,coverage:coverage(f.rentalCapacity),capacity:f.rentalCapacity,rph:s.rentalRph,
 costs:[['Reserved cloud compute',f.compute],['Storage & other costs',s.rentalExtras],['Extra API usage',f.rentalOverflow],['API fees for overflow',f.rentalOverflow>0?s.apiExtras:0]],initial:[['One-time setup',s.rentalSetup]],
 note:'Reserved hours are billed even when idle. This assumes the instance stops outside your selected schedule.'},
 {key:'api',title:'Pay per use · API',name:r.m.provider,upfront:0,monthly:f.apiMonthly,total:l.api,coverage:null,capacity:null,rph:null,
 costs:[['Input tokens',f.requests===null?null:f.requests*s.input*r.m.input/1e6],['Output tokens',f.requests===null?null:f.requests*s.output*r.m.output/1e6],['Platform & other fees',s.apiExtras]],initial:[],
 note:'No hardware to operate. Full demand is priced here; provider rate limits and service availability still need validation.'}
 ];
}
export function renderComparison(r){
 const cards=comparisonData(r),finite=cards.filter(c=>Number.isFinite(c.total)),best=finite.length===3?Math.min(...finite.map(c=>c.total)):null;
 const rows=items=>`<dl class="decision-rows">${items.map(([k,v])=>`<div><dt>${esc(k)}</dt><dd>${typeof v==='number'?money(v):esc(v??'Check advanced inputs')}</dd></div>`).join('')}</dl>`;
 const payback=v=>v===null?'No sustained payback within 10 years':`${num(v)} months`;
 return `<div class="decision-context"><h2>Compare your three options</h2><p>${esc(r.m.name)} · ${num(r.first.requests,0)} requests/month · ${r.months}-month comparison · monthly figures show the first month. All totals include overflow and entered fees.</p></div><div class="metrics decision-panels">${cards.map(c=>`<article class="metric decision-card" aria-label="${c.title}"><div class="eyebrow">${c.title}</div><h3>${esc(c.name)}</h3><div class="decision-badge">${best!==null&&c.total===best?'Lowest total over this period':'Planning estimate'}</div><div class="decision-monthly"><strong>${money(c.monthly)}</strong><span>per month · operating costs</span></div>${rows([['Upfront payment',c.upfront],[`${r.months}-month total`,c.total]])}<p class="decision-total-note">Total includes upfront payment and calendar-based monthly costs.</p><h4>What the monthly cost includes</h4>${rows(c.costs)}${c.initial.length?`<details><summary>Upfront cost breakdown</summary>${rows(c.initial)}</details>`:''}<h4>${c.key==='api'?'Usage being priced':'How much work it handles'}</h4>${c.key==='api'?rows([
 ['Requests / month',num(r.first.requests,0)],['Input tokens / month',num(r.first.requests*r.s.input,0)],['Output tokens / month',num(r.first.requests*r.s.output,0)],['Input price / 1M tokens',money(r.m.input)],['Output price / 1M tokens',money(r.m.output)]
 ]):rows([['Work handled by this system',c.coverage===null?'Check advanced inputs':num(c.coverage*100)+'%'],['Work sent to API',c.coverage===null?'Check advanced inputs':num((1-c.coverage)*100)+'%'],['Estimated capacity / month',num(c.capacity,0)+' requests'],['Estimated processing rate',num(c.rph,0)+' requests/hour'],['Usable model memory',num(c.key==='buy'?r.s.localAvailable:r.s.rentalAvailable)+' GB']])}${c.key==='rent'?rows([['Whole-instance rate',money(r.r.hourly)+'/hour'],['Reserved time / month',num(r.first.hours,0)+' hours']]):''}${c.key==='buy'?`<h4>When buying pays back</h4>${rows([['Versus API',payback(r.paybackApi)],['Versus renting',payback(r.paybackRent)]])}`:''}<p class="decision-tradeoff">${esc(c.note)}</p><p class="decision-provenance">${c.key==='buy'?'Equipment price may be a planning allowance; power, support and performance are assumptions unless overridden.':c.key==='rent'?'Rental rate is published; performance and extra fees are planning assumptions unless overridden.':'Token prices are published; usage and fees are planning assumptions unless overridden. No cache savings assumed.'}</p><a href="${esc(c.key==='buy'?r.h.source:c.key==='rent'?r.r.source:r.m.apiSource)}" target="_blank" rel="noreferrer">${c.key==='buy'?'System specifications':c.key==='rent'?'Rental price source':'API price source'} ↗</a></article>`).join('')}</div>`;
}
