const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=(v,d=1)=>Number.isFinite(v)?v.toLocaleString('en-US',{maximumFractionDigits:d}):'Unavailable';
const money=v=>Number.isFinite(v)?new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(v):'Unavailable';
export function comparisonData(r){
 const {s,first:f,last:l}=r;
 const coverage=capacity=>Number.isFinite(capacity)&&Number.isFinite(f.requests)?(f.requests>0?Math.min(1,capacity/f.requests):1):null;
 return [
 {key:'buy',title:'Buy hardware',name:r.h.name,upfront:r.capital,monthly:f.buyMonthly,amortized:r.amortized.buy,total:l.buy,coverage:coverage(f.localCapacity),capacity:f.localCapacity,rph:s.localRph,
 costs:[['IT electricity',r.power?.it],['Cooling electricity',r.power?.cooling],['Support & other costs',s.localExtras*(r.localUnits??1)]],
 initial:[['Equipment after discount',r.purchase===null?null:r.purchase*(1-s.purchaseDiscount/100)*(r.localUnits??1)],['Setup, tax & other extras',s.localSetup*(r.localUnits??1)]],
 note:'You own and maintain all required systems. No API calls are included in this path.'},
 {key:'rent',title:'Rent hardware',name:r.r.name,upfront:r.rentReady?s.rentalSetup*r.rentalUnits:null,monthly:f.rentMonthly,amortized:r.amortized.rent,total:l.rent,coverage:coverage(f.rentalCapacity),capacity:f.rentalCapacity,rph:s.rentalRph,
 costs:[['Reserved cloud compute',f.compute],['Storage & other costs',s.rentalExtras*(r.rentalUnits??1)]],initial:[['One-time setup',s.rentalSetup*(r.rentalUnits??1)]],
 note:'All required instances are rented. No API calls are included. Reserved hours are billed even when idle. This assumes the instance stops outside your selected schedule.'},
 {key:'api',title:'Pay per use · API',name:r.m.provider,upfront:0,monthly:f.apiMonthly,amortized:r.amortized.api,total:l.api,coverage:null,capacity:null,rph:null,
 costs:[['Input tokens',f.requests===null?null:f.requests*s.input*r.m.input/1e6],['Output tokens',f.requests===null?null:f.requests*s.output*r.m.output/1e6],['Platform & other fees',s.apiExtras]],initial:[],
 note:'No hardware to operate. Full demand is priced here; provider rate limits and service availability still need validation.'}
 ];
}
export function renderComparison(r){
 const cards=comparisonData(r),finite=cards.filter(c=>Number.isFinite(r.decisionCosts[c.key])&&(c.key!=='buy'||r.buyEligible)),best=finite.length?Math.min(...finite.map(c=>r.decisionCosts[c.key])):null;
 const rows=items=>`<dl class="decision-rows">${items.map(([k,v])=>`<div><dt>${esc(k)}</dt><dd>${typeof v==='number'?money(v):esc(v??'Unavailable')}</dd></div>`).join('')}</dl>`;
 const payback=v=>v===null?'No payback before refresh':`${num(v)} months`;
 return `<div class="decision-context"><h2>Compare your three options</h2><p>${esc(r.m.name)} · ${num(r.first.requests,0)} requests/month · ${r.months}-month comparison · monthly figures show the first month. Each path serves the entire workload independently; totals include entered fees.</p></div><div class="metrics decision-panels">${cards.map(c=>c.key!=='api'&&r.verification&&!r.verification[c.key]?`<article class="metric decision-card" aria-label="${c.title}"><div class="eyebrow">${c.title}</div><h3>No verified configuration available</h3><p>No hardware recommendation or cost projection. A reviewed validation record for the exact model, runtime, complete system and workload is required.</p></article>`:`<article class="metric decision-card" aria-label="${c.title}"><div class="eyebrow">${c.title}</div><h3>${esc(c.name)}</h3>${c.key!=='api'?`<p class="deployment-count">${num(c.key==='buy'?r.localUnits:r.rentalUnits,0)} × configured ${c.key==='buy'?'system / cluster':'instance'} · totals below cover all units</p>`:'<p class="deployment-count">API only · entire workload</p>'}<div class="decision-badge">${best!==null&&r.decisionCosts[c.key]===best?'Lowest cost before refresh':'Planning estimate'}</div>${c.key!=='api'&&c.capacity===null?'<p class="status warn">This configuration cannot serve the model. Select compatible hardware; adding replicas does not combine their memory.</p>':''}<div class="decision-monthly"><strong>${money(c.monthly)}</strong><span>monthly cost · operations only</span></div>${rows([['Upfront cost',c.upfront],['Amortized all-in / month',c.amortized]])}<p class="decision-total-note">${num(r.amortizationMonths)} months · ${esc(r.amortizationBasis)}. Amortized cost includes upfront and recurring costs; do not add it to the monthly figure.</p>${rows([[`Cost by refresh (${num(r.usefulMonths)} mo)`,r.decisionCosts[c.key]]])}<h4>What the monthly cost includes</h4>${rows(c.costs)}${c.initial.length?`<details><summary>Upfront cost breakdown</summary>${rows(c.initial)}</details>`:''}<h4>${c.key==='api'?'Usage being priced':'How much work it handles'}</h4>${c.key==='api'?rows([
 ['Requests / month',num(r.first.requests,0)],['Input tokens / month',num(r.first.requests*r.s.input,0)],['Output tokens / month',num(r.first.requests*r.s.output,0)],['Input price / 1M tokens',money(r.m.input)],['Output price / 1M tokens',money(r.m.output)]
 ]):rows([['Work handled by this system',c.coverage===null?'Unavailable':num(c.coverage*100)+'%'],['Systems / instances needed',num(c.key==='buy'?r.localUnits:r.rentalUnits,0)],['Fleet capacity / month',num(c.capacity,0)+' requests'],['Rate per system',num(c.rph,0)+' requests/hour'],['Model memory per system',num(c.key==='buy'?r.s.localAvailable:r.s.rentalAvailable)+' GB']])}${c.key!=='api'?`<h4>Input & output speed</h4><p class="phase-emphasis">Task balance: ${r.phases[c.key].ratio===null?'input-only':num(r.phases[c.key].ratio)+' input tokens per output token'}</p>${rows([
 ['Input processing (prefill)',num(r.phases[c.key].prefill,0)+' tokens/sec'],
 ['Output generation (decode)',num(r.phases[c.key].decode,0)+' tokens/sec'],
 ['Hardware prefill : decode',r.phases[c.key].decode>0?num(r.phases[c.key].prefill/r.phases[c.key].decode)+' : 1':'Not calculable'],
 ['Task input : output ratio',r.phases[c.key].ratio===null?'Input-only':num(r.phases[c.key].ratio)+' : 1'],
 ['Time processing input',r.phases[c.key].prefillShare===null?'Not calculable':num(r.phases[c.key].prefillShare*100)+'%'],
 ['Time generating output',r.phases[c.key].decodeShare===null?'Not calculable':num(r.phases[c.key].decodeShare*100)+'%'],
 ['Fleet input demand',num(r.phases[c.key].requiredPrefill)+' tokens/sec'],
 ['Fleet output demand',num(r.phases[c.key].requiredDecode)+' tokens/sec']
 ])}<p class="decision-provenance">Speeds are per system or configured cluster at the selected concurrency; default estimates, not measured benchmarks. ${r.phases[c.key].prefillShare!==null?(r.phases[c.key].prefillShare>.5?'Input processing dominates this task.':'Output generation dominates this task.'):''} Matching the task ratio gives equal time in each phase; the time shares reveal the bottleneck. Phase times exclude queueing and network delay.</p>`:''}${c.key==='rent'?rows([['Whole-instance rate',money(r.r.hourly)+'/hour'],['Reserved time / month',num(r.first.hours,0)+' hours']]):''}${c.key==='buy'?`<h4>When buying pays back</h4>${rows([['Versus API',payback(r.paybackApi)],['Versus renting',payback(r.paybackRent)]])}`:''}<p class="decision-tradeoff">${esc(c.note)}</p><p class="decision-provenance">${c.key==='buy'?'Equipment price may be a planning allowance; power, support and performance are assumptions unless overridden.':c.key==='rent'?'Rental rate is published; performance and extra fees are planning assumptions unless overridden.':'Token prices are published; usage and fees are planning assumptions unless overridden. No cache savings assumed.'}</p><a href="${esc(c.key==='buy'?r.h.source:c.key==='rent'?r.r.source:r.m.apiSource)}" target="_blank" rel="noreferrer">${c.key==='buy'?'System specifications':c.key==='rent'?'Rental price source':'API price source'} ↗</a></article>`).join('')}</div>`;
}
